import { toEntityId, toISODateString } from '@granit/types';

import type {
  PaymentAvailableMethodResponse,
  PaymentDisputeResponse,
  PaymentMethodResponse,
  PaymentRefundResponse,
  PaymentTransactionResponse,
} from '@granit/payments';
import type { Mutable } from '@granit/testing';
import type { CurrencyCode } from '@granit/types';

export const sampleTransactions: Mutable<PaymentTransactionResponse>[] = [
  {
    id: toEntityId<'PaymentTransaction'>('txn_4kLm8nPqRs'),
    invoiceId: toEntityId<'Invoice'>('inv_001'),
    status: 'Succeeded',
    amount: 24900,
    currency: 'EUR' as CurrencyCode,
    providerName: 'Stripe',
    providerTransactionId: 'pi_stripe_001',
    paymentMethodId: toEntityId<'PaymentMethod'>('pm_visa_4242'),
    actionUrl: null,
    idempotencyKey: 'idem_001',
    failureCode: null,
    succeededAt: toISODateString('2026-03-28T14:22:00Z'),
    canceledAt: null,
    refunds: [],
    disputes: [],
    tenantId: toEntityId<'Tenant'>('tenant_01'),
  },
  {
    id: toEntityId<'PaymentTransaction'>('txn_7xYzAbCdEf'),
    invoiceId: toEntityId<'Invoice'>('inv_002'),
    status: 'Created',
    amount: 5000,
    currency: 'EUR' as CurrencyCode,
    providerName: 'Stripe',
    providerTransactionId: 'pi_stripe_002',
    paymentMethodId: toEntityId<'PaymentMethod'>('pm_mc_5555'),
    actionUrl: null,
    idempotencyKey: 'idem_002',
    failureCode: null,
    succeededAt: null,
    canceledAt: null,
    refunds: [],
    disputes: [],
    tenantId: toEntityId<'Tenant'>('tenant_01'),
  },
  {
    id: toEntityId<'PaymentTransaction'>('txn_2gHiJkLmNo'),
    invoiceId: toEntityId<'Invoice'>('inv_003'),
    status: 'Failed',
    amount: 12000,
    currency: 'USD' as CurrencyCode,
    providerName: 'Stripe',
    providerTransactionId: 'pi_stripe_003',
    paymentMethodId: toEntityId<'PaymentMethod'>('pm_visa_1234'),
    actionUrl: null,
    idempotencyKey: 'idem_003',
    failureCode: 'card_declined',
    succeededAt: null,
    canceledAt: null,
    refunds: [],
    disputes: [],
    tenantId: toEntityId<'Tenant'>('tenant_01'),
  },
  {
    id: toEntityId<'PaymentTransaction'>('txn_9pQrStUvWx'),
    invoiceId: toEntityId<'Invoice'>('inv_001'),
    status: 'Succeeded',
    amount: 7500,
    currency: 'EUR' as CurrencyCode,
    providerName: 'Stripe',
    providerTransactionId: 'pi_stripe_004',
    paymentMethodId: toEntityId<'PaymentMethod'>('pm_visa_4242'),
    actionUrl: null,
    idempotencyKey: 'idem_004',
    failureCode: null,
    succeededAt: toISODateString('2026-03-20T11:00:00Z'),
    canceledAt: null,
    refunds: [],
    disputes: [],
    tenantId: toEntityId<'Tenant'>('tenant_01'),
  },
  {
    id: toEntityId<'PaymentTransaction'>('txn_3aBcDeFgHi'),
    invoiceId: toEntityId<'Invoice'>('inv_004'),
    status: 'Processing',
    amount: 35000,
    currency: 'EUR' as CurrencyCode,
    providerName: 'Stripe',
    providerTransactionId: 'pi_stripe_005',
    paymentMethodId: toEntityId<'PaymentMethod'>('pm_sepa_6789'),
    actionUrl: null,
    idempotencyKey: 'idem_005',
    failureCode: null,
    succeededAt: null,
    canceledAt: null,
    refunds: [],
    disputes: [],
    tenantId: toEntityId<'Tenant'>('tenant_01'),
  },
];

export const sampleRefunds: Mutable<PaymentRefundResponse>[] = [
  {
    id: toEntityId<'PaymentRefund'>('ref_001'),
    amount: 7500,
    currency: 'EUR' as CurrencyCode,
    status: 'Succeeded',
    providerRefundId: 'pr_stripe_001',
    reason: 'Customer requested cancellation before event',
    createdAt: toISODateString('2026-03-22T09:15:00Z'),
    completedAt: toISODateString('2026-03-22T09:20:00Z'),
  },
  {
    id: toEntityId<'PaymentRefund'>('ref_002'),
    amount: 5000,
    currency: 'EUR' as CurrencyCode,
    status: 'Pending',
    providerRefundId: 'pr_stripe_002',
    reason: 'Partial refund — unused months',
    createdAt: toISODateString('2026-04-03T14:00:00Z'),
    completedAt: null,
  },
];

export const sampleDisputes: Mutable<PaymentDisputeResponse>[] = [
  {
    id: toEntityId<'PaymentDispute'>('dis_001'),
    providerDisputeId: 'dp_stripe_001',
    status: 'Open',
    reason: 'Customer claims unauthorized transaction',
    amount: 35000,
    currency: 'EUR' as CurrencyCode,
    createdAt: toISODateString('2026-04-04T10:00:00Z'),
    resolvedAt: null,
  },
];

export const samplePaymentMethods: Mutable<PaymentMethodResponse>[] = [
  {
    id: toEntityId<'PaymentMethod'>('pm_visa_4242'),
    type: 'Card',
    providerName: 'Stripe',
    providerMethodId: 'pm_stripe_visa_4242',
    displayLabel: 'Visa ending in 4242',
    isDefault: true,
    expiresAt: toISODateString('2028-12-31T23:59:59Z'),
    tenantId: toEntityId<'Tenant'>('tenant_01'),
  },
  {
    id: toEntityId<'PaymentMethod'>('pm_mc_5555'),
    type: 'Card',
    providerName: 'Stripe',
    providerMethodId: 'pm_stripe_mc_5555',
    displayLabel: 'Mastercard ending in 5555',
    isDefault: false,
    expiresAt: toISODateString('2027-03-31T23:59:59Z'),
    tenantId: toEntityId<'Tenant'>('tenant_01'),
  },
  {
    id: toEntityId<'PaymentMethod'>('pm_sepa_6789'),
    type: 'BankTransfer',
    providerName: 'Stripe',
    providerMethodId: 'pm_stripe_sepa_6789',
    displayLabel: 'SEPA ending in 6789',
    isDefault: false,
    expiresAt: null,
    tenantId: toEntityId<'Tenant'>('tenant_01'),
  },
];

export const sampleAvailableMethods: PaymentAvailableMethodResponse[] = [
  {
    methodType: 'BankTransfer',
    providerName: 'Stripe',
    displayLabel: 'iDEAL',
    category: 'BankTransfer',
    capability: null,
  },
  {
    methodType: 'BankTransfer',
    providerName: 'Stripe',
    displayLabel: 'Bancontact',
    category: 'BankTransfer',
    capability: null,
  },
];
