// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/customer-balance.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const customerBalanceConstraints = {
  "AdminCreditRequest": {
    "partyId": {
      "required": true,
      "format": "uuid"
    },
    "amount": {
      "required": true,
      "pattern": "^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$",
      "format": "double",
      "exclusiveMinimum": 0
    },
    "currency": {
      "required": true,
      "maxLength": 3,
      "minLength": 3
    },
    "source": {
      "required": true,
      "maxLength": 50
    },
    "reason": {
      "required": true,
      "maxLength": 500
    },
    "expiresAt": {
      "format": "date-time"
    }
  },
  "AdminDebitRequest": {
    "partyId": {
      "required": true,
      "format": "uuid"
    },
    "amount": {
      "required": true,
      "pattern": "^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$",
      "format": "double",
      "exclusiveMinimum": 0
    },
    "currency": {
      "required": true,
      "maxLength": 3,
      "minLength": 3
    },
    "reason": {
      "required": true,
      "maxLength": 500
    },
    "referenceId": {
      "format": "uuid"
    },
    "referenceType": {
      "maxLength": 64
    }
  }
} satisfies Record<string, SchemaConstraints>;
