// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/invoicing.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const invoicingConstraints = {
  "CancelInvoiceRequest": {
    "reason": {
      "maxLength": 1000
    }
  },
  "FinalizeInvoiceRequest": {
    "issuedAt": {
      "required": true,
      "format": "date-time"
    },
    "dueAt": {
      "format": "date-time"
    },
    "comment": {
      "maxLength": 500
    }
  },
  "InvoiceCreateRequest": {
    "partyId": {
      "required": true,
      "format": "uuid"
    },
    "documentType": {
      "required": true
    },
    "currency": {
      "required": true,
      "maxLength": 3
    },
    "collectionMethod": {
      "required": true
    },
    "billingReason": {
      "required": true
    },
    "parentInvoiceId": {
      "format": "uuid"
    },
    "creditNoteReason": {
      "maxLength": 500
    },
    "periodStart": {
      "format": "date-time"
    },
    "periodEnd": {
      "format": "date-time"
    }
  },
  "MarkInvoiceUncollectibleRequest": {
    "reason": {
      "maxLength": 1000
    }
  },
  "WorkflowTransitionRequest": {
    "targetState": {
      "required": true
    },
    "comment": {}
  }
} satisfies Record<string, SchemaConstraints>;
