// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/taxonomy.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const taxonomyConstraints = {
  "AssignCategoryRequest": {
    "targetType": {
      "required": true,
      "maxLength": 256
    },
    "targetId": {
      "required": true,
      "format": "uuid"
    }
  },
  "AssignTagRequest": {
    "targetType": {
      "required": true,
      "maxLength": 256
    },
    "targetId": {
      "required": true,
      "format": "uuid"
    }
  },
  "CreateCategoryRequest": {
    "scope": {
      "required": true,
      "maxLength": 64
    },
    "name": {
      "required": true,
      "maxLength": 100,
      "pattern": "^[^/]+$"
    },
    "parentId": {
      "format": "uuid"
    },
    "iconName": {
      "maxLength": 100
    },
    "hideOnEntityCard": {}
  },
  "CreateTagRequest": {
    "scope": {
      "required": true,
      "maxLength": 64
    },
    "name": {
      "required": true,
      "maxLength": 50
    },
    "color": {
      "required": true,
      "pattern": "^#[0-9A-Fa-f]{6}$"
    },
    "hideOnEntityCard": {}
  },
  "MoveCategoryRequest": {
    "newParentId": {
      "format": "uuid"
    }
  },
  "UpdateCategoryRequest": {
    "concurrencyStamp": {
      "required": true
    },
    "name": {
      "maxLength": 100,
      "pattern": "^[^/]+$"
    },
    "iconName": {
      "maxLength": 100
    },
    "hideOnEntityCard": {}
  },
  "UpdateTagRequest": {
    "concurrencyStamp": {
      "required": true
    },
    "name": {
      "maxLength": 50
    },
    "color": {
      "pattern": "^#[0-9A-Fa-f]{6}$"
    },
    "hideOnEntityCard": {}
  }
} satisfies Record<string, SchemaConstraints>;
