// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/multi-tenancy.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const multiTenancyConstraints = {
  "CreateTenantRequest": {
    "name": {
      "required": true,
      "maxLength": 256
    },
    "identifier": {
      "required": true,
      "maxLength": 64,
      "pattern": "^[a-z0-9-]+$"
    },
    "contactEmail": {
      "maxLength": 256,
      "format": "email"
    },
    "jurisdiction": {
      "maxLength": 16
    }
  },
  "UpdateTenantRequest": {
    "name": {
      "required": true,
      "maxLength": 256
    },
    "concurrencyStamp": {
      "required": true
    },
    "contactEmail": {
      "maxLength": 256,
      "format": "email"
    },
    "jurisdiction": {
      "maxLength": 16
    }
  }
} satisfies Record<string, SchemaConstraints>;
