import type { AuditEntry } from '@granit/auditing';
import type { Mutable } from '@granit/testing';

export const mockAuditEntries: Mutable<AuditEntry>[] = [
  {
    id: 'audit-001' as AuditEntry['id'],
    timestamp: '2026-02-27T08:00:00Z' as AuditEntry['timestamp'],
    userId: 'user-001' as AuditEntry['userId'],
    userName: 'Marie Dupont',
    category: 'DataMutation',
    ipAddress: '10.0.1.45',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 1,
  },
  {
    id: 'audit-002' as AuditEntry['id'],
    timestamp: '2026-02-27T09:00:00Z' as AuditEntry['timestamp'],
    userId: 'user-001' as AuditEntry['userId'],
    userName: 'Marie Dupont',
    category: 'DataMutation',
    ipAddress: '10.0.1.45',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 2,
  },
  {
    id: 'audit-003' as AuditEntry['id'],
    timestamp: '2026-02-27T10:00:00Z' as AuditEntry['timestamp'],
    userId: 'user-005' as AuditEntry['userId'],
    userName: 'Claire Moreau',
    category: 'ConfigurationChange',
    ipAddress: '10.0.2.12',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 1,
  },
  {
    id: 'audit-004' as AuditEntry['id'],
    timestamp: '2026-02-26T14:00:00Z' as AuditEntry['timestamp'],
    userId: 'user-010' as AuditEntry['userId'],
    userName: 'François Lambert',
    category: 'ConfigurationChange',
    ipAddress: '10.0.3.88',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 1,
  },
  {
    id: 'audit-005' as AuditEntry['id'],
    timestamp: '2026-02-26T16:00:00Z' as AuditEntry['timestamp'],
    userId: 'user-001' as AuditEntry['userId'],
    userName: 'Marie Dupont',
    category: 'DataMutation',
    ipAddress: '10.0.1.45',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 3,
  },
  {
    id: 'audit-006' as AuditEntry['id'],
    timestamp: '2026-02-25T09:00:00Z' as AuditEntry['timestamp'],
    userId: 'user-005' as AuditEntry['userId'],
    userName: 'Claire Moreau',
    category: 'DataMutation',
    ipAddress: '10.0.2.12',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 1,
  },
  {
    id: 'audit-007' as AuditEntry['id'],
    timestamp: '2026-02-24T11:00:00Z' as AuditEntry['timestamp'],
    userId: null as unknown as AuditEntry['userId'],
    userName: null,
    category: 'DataAccess',
    ipAddress: '10.0.4.1',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 0,
  },
  {
    id: 'audit-008' as AuditEntry['id'],
    timestamp: '2026-02-23T08:00:00Z' as AuditEntry['timestamp'],
    userId: 'user-010' as AuditEntry['userId'],
    userName: 'François Lambert',
    category: 'AccessDenied',
    ipAddress: '10.0.3.88',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 0,
  },
  {
    id: 'audit-009' as AuditEntry['id'],
    timestamp: '2026-02-22T10:00:00Z' as AuditEntry['timestamp'],
    userId: 'user-001' as AuditEntry['userId'],
    userName: 'Marie Dupont',
    category: 'DataMutation',
    ipAddress: '10.0.1.45',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 2,
  },
  {
    id: 'audit-010' as AuditEntry['id'],
    timestamp: '2026-02-20T14:00:00Z' as AuditEntry['timestamp'],
    userId: 'user-010' as AuditEntry['userId'],
    userName: 'François Lambert',
    category: 'ConfigurationChange',
    ipAddress: '10.0.3.88',
    tenantId: null,
    correlationId: null,
    entityChangeCount: 1,
  },
];
