// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/ai.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const aiConstraints = {
  "AIChatMessageRequest": {
    "role": {
      "required": true
    },
    "content": {
      "required": true
    }
  },
  "AIChatRequest": {
    "messages": {
      "required": true,
      "granitValidator": "Validation:MaxChatMessages"
    }
  },
  "AIEmbeddingRequest": {
    "inputs": {
      "required": true,
      "maxLength": 32000,
      "granitValidator": "Validation:MaxEmbeddingInputs"
    }
  },
  "AIWorkspaceCreateRequest": {
    "key": {
      "required": true,
      "maxLength": 128,
      "pattern": "^[a-z0-9][a-z0-9-]*$"
    },
    "provider": {
      "required": true
    },
    "model": {
      "required": true
    },
    "displayName": {},
    "systemPrompt": {},
    "temperature": {
      "pattern": "^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?(?:[eE][+-]?\\d+)?$",
      "format": "float"
    },
    "maxOutputTokens": {
      "format": "int32"
    }
  },
  "AIWorkspaceUpdateRequest": {
    "provider": {
      "required": true
    },
    "model": {
      "required": true
    },
    "displayName": {},
    "systemPrompt": {},
    "temperature": {
      "pattern": "^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?(?:[eE][+-]?\\d+)?$",
      "format": "float"
    },
    "maxOutputTokens": {
      "format": "int32"
    },
    "activated": {}
  }
} satisfies Record<string, SchemaConstraints>;
