import type { AdminAppSetting } from '@granit/settings';
import type { Mutable } from '@granit/testing';

export const mockAppSettings: Mutable<AdminAppSetting>[] = [
  {
    key: 'audit.retention_days',
    label: 'Audit Log Retention',
    description: 'Number of days to retain audit logs before automatic purge.',
    defaultValue: '365',
    value: '1095',
    valueKind: 'Int',
    allowedValues: null,
    isEncrypted: false,
  },
  {
    key: 'auth.session_timeout_minutes',
    label: 'Session Timeout',
    description: 'Idle session timeout in minutes. Users will be logged out after this period.',
    defaultValue: '30',
    value: '30',
    valueKind: 'Int',
    allowedValues: null,
    isEncrypted: false,
  },
  {
    key: 'api.rate_limit_per_minute',
    label: 'API Rate Limit',
    description: 'Maximum API requests allowed per minute per user.',
    defaultValue: '100',
    value: '100',
    valueKind: 'Int',
    allowedValues: null,
    isEncrypted: false,
  },
  {
    key: 'ui.default_page_size',
    label: 'Default Page Size',
    description: 'Default number of items per page in list views.',
    defaultValue: '20',
    value: '20',
    valueKind: 'Int',
    allowedValues: ['10', '20', '50', '100'],
    isEncrypted: false,
  },
  {
    key: 'notifications.email_enabled',
    label: 'Email Notifications',
    description: 'Enable email notifications for system events and alerts.',
    defaultValue: 'false',
    value: 'true',
    valueKind: 'Bool',
    allowedValues: null,
    isEncrypted: false,
  },
  {
    key: 'system.maintenance_mode',
    label: 'Maintenance Mode',
    description: 'Enable maintenance mode to block user access during scheduled maintenance.',
    defaultValue: 'false',
    value: 'false',
    valueKind: 'Bool',
    allowedValues: null,
    isEncrypted: false,
  },
  {
    key: 'ui.theme',
    label: 'Theme',
    description: 'Default UI theme applied to new sessions.',
    defaultValue: 'system',
    value: 'light',
    valueKind: 'String',
    allowedValues: ['light', 'dark', 'system'],
    isEncrypted: false,
  },
  {
    key: 'integrations.stripe_secret_key',
    label: 'Stripe Secret Key',
    description: 'API key used to sign Stripe webhook requests.',
    defaultValue: null,
    value: '***',
    valueKind: 'String',
    allowedValues: null,
    isEncrypted: true,
  },
];

/** In-memory settings store per scope. */
export const mockSettingsStore: Record<string, Record<string, string | null>> = {
  user: {
    'Granit.Localization.PreferredCulture': 'fr',
    'Granit.Timing.PreferredTimezone': 'Europe/Brussels',
  },
  global: {
    'audit.retention_days': '1095',
    'auth.session_timeout_minutes': '30',
    'api.rate_limit_per_minute': '100',
    'ui.default_page_size': '20',
    'notifications.email_enabled': 'true',
    'system.maintenance_mode': 'false',
    'ui.theme': 'light',
  },
  tenant: {
    'ui.default_page_size': '20',
    'notifications.email_enabled': 'true',
    'ui.theme': 'light',
  },
};
