import { toEntityId, toISODateString } from '@granit/types';

import type {
  NotificationDefinition,
  NotificationPreference,
  UserNotification,
} from '@granit/notifications';
import type { Mutable } from '@granit/testing';
import type { UserId } from '@granit/types';

const adminUserId = toEntityId<'User'>('user-admin-001') as UserId;

export const mockNotifications: Mutable<UserNotification>[] = [
  {
    id: toEntityId<'UserNotification'>('notif-001'),
    notificationId: toEntityId<'Notification'>('ntype-001'),
    notificationTypeName: 'user_registered',
    severity: 'Info',
    data: {
      title: 'New user registered',
      body: 'User jean.dupont@example.com has registered and is pending approval.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: 'User',
    relatedEntityId: 'user-005',
    state: 'Unread',
    createdAt: toISODateString('2026-03-12T09:55:00Z'),
    readAt: null,
  },
  {
    id: toEntityId<'UserNotification'>('notif-002'),
    notificationId: toEntityId<'Notification'>('ntype-002'),
    notificationTypeName: 'country_updated',
    severity: 'Success',
    data: {
      title: 'Country reference updated',
      body: 'Country "Belgium" (BE) has been updated by admin@granit-showcase.local.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: 'Country',
    relatedEntityId: 'BE',
    state: 'Unread',
    createdAt: toISODateString('2026-03-12T09:30:00Z'),
    readAt: null,
  },
  {
    id: toEntityId<'UserNotification'>('notif-003'),
    notificationId: toEntityId<'Notification'>('ntype-003'),
    notificationTypeName: 'config_changed',
    severity: 'Warning',
    data: {
      title: 'Configuration change detected',
      body: 'Feature flag "maintenance_mode" has been toggled ON.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: 'Config',
    relatedEntityId: 'maintenance_mode',
    state: 'Unread',
    createdAt: toISODateString('2026-03-12T09:00:00Z'),
    readAt: null,
  },
  {
    id: toEntityId<'UserNotification'>('notif-004'),
    notificationId: toEntityId<'Notification'>('ntype-004'),
    notificationTypeName: 'security_alert',
    severity: 'Error',
    data: {
      title: 'Authentication failure spike',
      body: '15 failed login attempts detected in the last 10 minutes.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: null,
    relatedEntityId: null,
    state: 'Unread',
    createdAt: toISODateString('2026-03-12T08:00:00Z'),
    readAt: null,
  },
  {
    id: toEntityId<'UserNotification'>('notif-005'),
    notificationId: toEntityId<'Notification'>('ntype-005'),
    notificationTypeName: 'user_role_changed',
    severity: 'Info',
    data: {
      title: 'User role updated',
      body: 'User marie.martin has been granted the granit-showcase-admin role.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: 'User',
    relatedEntityId: 'user-003',
    state: 'Read',
    createdAt: toISODateString('2026-03-12T06:00:00Z'),
    readAt: toISODateString('2026-03-12T07:00:00Z'),
  },
  {
    id: toEntityId<'UserNotification'>('notif-006'),
    notificationId: toEntityId<'Notification'>('ntype-006'),
    notificationTypeName: 'country_updated',
    severity: 'Warning',
    data: { title: 'Country deactivated', body: 'Country "Kosovo" (XK) has been deactivated.' },
    recipientUserId: adminUserId,
    relatedEntityType: 'Country',
    relatedEntityId: 'XK',
    state: 'Read',
    createdAt: toISODateString('2026-03-12T04:00:00Z'),
    readAt: toISODateString('2026-03-12T05:00:00Z'),
  },
  {
    id: toEntityId<'UserNotification'>('notif-007'),
    notificationId: toEntityId<'Notification'>('ntype-007'),
    notificationTypeName: 'service_health',
    severity: 'Success',
    data: {
      title: 'Database backup completed',
      body: 'Nightly PostgreSQL backup completed successfully. Size: 2.4 GB.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: null,
    relatedEntityId: null,
    state: 'Read',
    createdAt: toISODateString('2026-03-12T02:00:00Z'),
    readAt: toISODateString('2026-03-12T03:00:00Z'),
  },
  {
    id: toEntityId<'UserNotification'>('notif-008'),
    notificationId: toEntityId<'Notification'>('ntype-008'),
    notificationTypeName: 'audit_export',
    severity: 'Info',
    data: {
      title: 'Audit log export ready',
      body: 'Your requested audit log export (2026-02-01 to 2026-02-28) is ready for download.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: null,
    relatedEntityId: null,
    state: 'Read',
    createdAt: toISODateString('2026-03-11T22:00:00Z'),
    readAt: toISODateString('2026-03-12T00:00:00Z'),
  },
  {
    id: toEntityId<'UserNotification'>('notif-009'),
    notificationId: toEntityId<'Notification'>('ntype-009'),
    notificationTypeName: 'service_health',
    severity: 'Error',
    data: {
      title: 'Service degradation detected',
      body: 'FHIR Server response time exceeded 1500ms threshold.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: null,
    relatedEntityId: null,
    state: 'Read',
    createdAt: toISODateString('2026-03-11T16:00:00Z'),
    readAt: toISODateString('2026-03-11T18:00:00Z'),
  },
  {
    id: toEntityId<'UserNotification'>('notif-010'),
    notificationId: toEntityId<'Notification'>('ntype-010'),
    notificationTypeName: 'country_updated',
    severity: 'Success',
    data: {
      title: 'New country created',
      body: 'Country "South Sudan" (SS) has been added to the reference data.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: 'Country',
    relatedEntityId: 'SS',
    state: 'Read',
    createdAt: toISODateString('2026-03-11T10:00:00Z'),
    readAt: toISODateString('2026-03-11T12:00:00Z'),
  },
  {
    id: toEntityId<'UserNotification'>('notif-011'),
    notificationId: toEntityId<'Notification'>('ntype-011'),
    notificationTypeName: 'user_registered',
    severity: 'Warning',
    data: {
      title: 'User account disabled',
      body: 'User account for pierre.leroy@example.com has been disabled after 30 days of inactivity.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: 'User',
    relatedEntityId: 'user-008',
    state: 'Read',
    createdAt: toISODateString('2026-03-11T04:00:00Z'),
    readAt: toISODateString('2026-03-11T06:00:00Z'),
  },
  {
    id: toEntityId<'UserNotification'>('notif-012'),
    notificationId: toEntityId<'Notification'>('ntype-012'),
    notificationTypeName: 'security_alert',
    severity: 'Warning',
    data: {
      title: 'Certificate renewal reminder',
      body: 'TLS certificate for api.granit-showcase.local expires in 14 days.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: null,
    relatedEntityId: null,
    state: 'Unread',
    createdAt: toISODateString('2026-03-10T22:00:00Z'),
    readAt: null,
  },
  {
    id: toEntityId<'UserNotification'>('notif-013'),
    notificationId: toEntityId<'Notification'>('ntype-013'),
    notificationTypeName: 'service_health',
    severity: 'Success',
    data: {
      title: 'Scheduled maintenance completed',
      body: 'Maintenance window completed. All services are operational.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: null,
    relatedEntityId: null,
    state: 'Read',
    createdAt: toISODateString('2026-03-10T16:00:00Z'),
    readAt: toISODateString('2026-03-10T18:00:00Z'),
  },
  {
    id: toEntityId<'UserNotification'>('notif-014'),
    notificationId: toEntityId<'Notification'>('ntype-014'),
    notificationTypeName: 'rgpd_request',
    severity: 'Info',
    data: {
      title: 'RGPD data erasure request',
      body: 'Data erasure request received for user ID usr-2024-0847. Action required within 30 days.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: 'User',
    relatedEntityId: 'usr-2024-0847',
    state: 'Unread',
    createdAt: toISODateString('2026-03-12T07:00:00Z'),
    readAt: null,
  },
  {
    id: toEntityId<'UserNotification'>('notif-015'),
    notificationId: toEntityId<'Notification'>('ntype-015'),
    notificationTypeName: 'service_health',
    severity: 'Warning',
    data: {
      title: 'Audit trail warning',
      body: 'Audit log storage usage at 85%. Consider archiving older entries.',
    },
    recipientUserId: adminUserId,
    relatedEntityType: null,
    relatedEntityId: null,
    state: 'Read',
    createdAt: toISODateString('2026-03-10T10:00:00Z'),
    readAt: toISODateString('2026-03-10T12:00:00Z'),
  },
];

/**
 * Registry of notification types returned by `GET /notifications/types`.
 *
 * Mirrors the bare `NotificationDefinition[]` the .NET endpoint produces. Every
 * `notificationTypeName` used in {@link mockNotificationPreferences} and
 * {@link mockNotifications} has a matching entry so the preferences UI lines up
 * with the seeded preference rows. `security_alert` and `rgpd_request` are
 * mandatory (`allowUserOptOut: false`) — the preferences panel hides them.
 */
export const mockNotificationDefinitions: NotificationDefinition[] = [
  {
    name: 'user_registered',
    defaultSeverity: 'Info',
    defaultChannels: ['InApp', 'Email'],
    displayName: 'User registered',
    description: 'A new user account has been created and is pending approval.',
    groupName: 'Users',
    allowUserOptOut: true,
  },
  {
    name: 'user_role_changed',
    defaultSeverity: 'Info',
    defaultChannels: ['InApp', 'Email'],
    displayName: 'User role changed',
    description: 'A role has been granted to or revoked from a user.',
    groupName: 'Users',
    allowUserOptOut: true,
  },
  {
    name: 'country_updated',
    defaultSeverity: 'Success',
    defaultChannels: ['InApp'],
    displayName: 'Country reference updated',
    description: 'A country in the reference data has been created, updated or deactivated.',
    groupName: 'Reference data',
    allowUserOptOut: true,
  },
  {
    name: 'config_changed',
    defaultSeverity: 'Warning',
    defaultChannels: ['InApp', 'Email'],
    displayName: 'Configuration changed',
    description: 'A feature flag or system configuration value has been changed.',
    groupName: 'System',
    allowUserOptOut: true,
  },
  {
    name: 'security_alert',
    defaultSeverity: 'Error',
    defaultChannels: ['InApp', 'Email', 'Push'],
    displayName: 'Security alert',
    description: 'A security-relevant event was detected (e.g. authentication failure spike).',
    groupName: 'Security',
    allowUserOptOut: false,
  },
  {
    name: 'service_health',
    defaultSeverity: 'Warning',
    defaultChannels: ['InApp', 'Email'],
    displayName: 'Service health',
    description:
      'Infrastructure or service health status changed (backups, degradation, maintenance).',
    groupName: 'System',
    allowUserOptOut: true,
  },
  {
    name: 'audit_export',
    defaultSeverity: 'Info',
    defaultChannels: ['InApp', 'Email'],
    displayName: 'Audit export ready',
    description: 'A requested audit log export has finished and is ready to download.',
    groupName: 'Compliance',
    allowUserOptOut: true,
  },
  {
    name: 'rgpd_request',
    defaultSeverity: 'Info',
    defaultChannels: ['InApp', 'Email', 'Push'],
    displayName: 'RGPD request',
    description:
      'A GDPR data subject request (access, erasure) requires action within the legal delay.',
    groupName: 'Compliance',
    allowUserOptOut: false,
  },
];

export const mockNotificationPreferences: NotificationPreference[] = [
  {
    id: toEntityId<'NotificationPreference'>('pref-001'),
    userId: adminUserId,
    notificationTypeName: 'user_registered',
    channelName: 'InApp',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-002'),
    userId: adminUserId,
    notificationTypeName: 'user_registered',
    channelName: 'Email',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-003'),
    userId: adminUserId,
    notificationTypeName: 'user_registered',
    channelName: 'Push',
    isEnabled: false,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-004'),
    userId: adminUserId,
    notificationTypeName: 'user_role_changed',
    channelName: 'InApp',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-005'),
    userId: adminUserId,
    notificationTypeName: 'user_role_changed',
    channelName: 'Email',
    isEnabled: false,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-006'),
    userId: adminUserId,
    notificationTypeName: 'user_role_changed',
    channelName: 'Push',
    isEnabled: false,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-007'),
    userId: adminUserId,
    notificationTypeName: 'country_updated',
    channelName: 'InApp',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-008'),
    userId: adminUserId,
    notificationTypeName: 'country_updated',
    channelName: 'Email',
    isEnabled: false,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-009'),
    userId: adminUserId,
    notificationTypeName: 'country_updated',
    channelName: 'Push',
    isEnabled: false,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-010'),
    userId: adminUserId,
    notificationTypeName: 'config_changed',
    channelName: 'InApp',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-011'),
    userId: adminUserId,
    notificationTypeName: 'config_changed',
    channelName: 'Email',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-012'),
    userId: adminUserId,
    notificationTypeName: 'config_changed',
    channelName: 'Push',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-013'),
    userId: adminUserId,
    notificationTypeName: 'security_alert',
    channelName: 'InApp',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-014'),
    userId: adminUserId,
    notificationTypeName: 'security_alert',
    channelName: 'Email',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-015'),
    userId: adminUserId,
    notificationTypeName: 'security_alert',
    channelName: 'Push',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-016'),
    userId: adminUserId,
    notificationTypeName: 'service_health',
    channelName: 'InApp',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-017'),
    userId: adminUserId,
    notificationTypeName: 'service_health',
    channelName: 'Email',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-018'),
    userId: adminUserId,
    notificationTypeName: 'service_health',
    channelName: 'Push',
    isEnabled: false,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-019'),
    userId: adminUserId,
    notificationTypeName: 'audit_export',
    channelName: 'InApp',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-020'),
    userId: adminUserId,
    notificationTypeName: 'audit_export',
    channelName: 'Email',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-021'),
    userId: adminUserId,
    notificationTypeName: 'audit_export',
    channelName: 'Push',
    isEnabled: false,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-022'),
    userId: adminUserId,
    notificationTypeName: 'rgpd_request',
    channelName: 'InApp',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-023'),
    userId: adminUserId,
    notificationTypeName: 'rgpd_request',
    channelName: 'Email',
    isEnabled: true,
  },
  {
    id: toEntityId<'NotificationPreference'>('pref-024'),
    userId: adminUserId,
    notificationTypeName: 'rgpd_request',
    channelName: 'Push',
    isEnabled: true,
  },
];
