// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/iot.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const iotConstraints = {
  "DeviceProvisionRequest": {
    "serialNumber": {
      "required": true,
      "maxLength": 128
    },
    "hardwareModel": {
      "required": true,
      "maxLength": 256
    },
    "firmwareVersion": {
      "required": true,
      "maxLength": 64
    },
    "label": {
      "maxLength": 256
    }
  },
  "DeviceUpdateRequest": {
    "concurrencyStamp": {
      "required": true
    },
    "firmwareVersion": {
      "maxLength": 64
    },
    "label": {
      "maxLength": 256
    }
  }
} satisfies Record<string, SchemaConstraints>;
