// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/parties.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const partiesConstraints = {
  "PartyAddressConfirmRequest": {
    "evidence": {
      "maxLength": 256
    }
  },
  "PartyAddressRequest": {
    "kind": {
      "required": true
    },
    "street1": {
      "required": true,
      "maxLength": 200
    },
    "city": {
      "required": true,
      "maxLength": 100
    },
    "postalCode": {
      "required": true,
      "maxLength": 20
    },
    "country": {
      "required": true,
      "maxLength": 2,
      "minLength": 2
    },
    "street2": {
      "maxLength": 200
    },
    "state": {
      "maxLength": 100
    },
    "isDefault": {},
    "label": {
      "maxLength": 128
    }
  },
  "PartyCreateRequest": {
    "kind": {
      "required": true
    },
    "name": {
      "required": true,
      "maxLength": 256
    },
    "defaultCurrency": {
      "required": true,
      "maxLength": 3,
      "minLength": 3
    },
    "roles": {},
    "website": {
      "maxLength": 2048
    },
    "language": {
      "maxLength": 16
    },
    "timezone": {
      "maxLength": 64
    },
    "taxId": {
      "maxLength": 64
    },
    "registrationNumber": {
      "maxLength": 64
    },
    "internalNotes": {
      "maxLength": 8000
    }
  },
  "PartyDuplicateMergeRequest": {
    "survivorId": {
      "required": true,
      "format": "uuid"
    },
    "choices": {},
    "reason": {
      "maxLength": 1000
    }
  },
  "PartyEmailRequest": {
    "address": {
      "required": true,
      "maxLength": 320,
      "format": "email"
    },
    "isPrimary": {},
    "label": {
      "maxLength": 64
    }
  },
  "PartyExternalMappingRequest": {
    "providerName": {
      "required": true,
      "maxLength": 64
    },
    "externalId": {
      "required": true,
      "maxLength": 256
    }
  },
  "PartyMergeRequest": {
    "loserId": {
      "required": true,
      "format": "uuid"
    },
    "choices": {},
    "reason": {
      "maxLength": 1000
    },
    "dryRun": {}
  },
  "PartyMetadataRequest": {
    "metadata": {
      "required": true
    }
  },
  "PartyPhoneRequest": {
    "kind": {
      "required": true
    },
    "number": {
      "required": true,
      "maxLength": 64
    },
    "isPrimary": {},
    "label": {
      "maxLength": 64
    }
  },
  "PartyRoleRequest": {
    "role": {
      "required": true
    }
  },
  "PartySuspendRequest": {
    "reason": {
      "maxLength": 512
    }
  },
  "PartyTaxStatusRequest": {
    "isExempt": {
      "required": true
    },
    "reverseCharge": {
      "required": true
    },
    "vatin": {
      "maxLength": 32
    },
    "evidenceBlobId": {
      "format": "uuid"
    }
  },
  "PartyUpdateRequest": {
    "name": {
      "required": true,
      "maxLength": 256
    },
    "website": {
      "maxLength": 2048
    },
    "language": {
      "maxLength": 16
    },
    "timezone": {
      "maxLength": 64
    },
    "internalNotes": {
      "maxLength": 8000
    }
  }
} satisfies Record<string, SchemaConstraints>;
