// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/api-keys.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const apiKeysConstraints = {
  "ApiKeyCreateRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "type": {
      "required": true
    },
    "environment": {
      "required": true,
      "granitValidator": "Validation:InvalidEnvironment"
    },
    "permissions": {
      "granitValidator": "Validation:MaxPermissions"
    },
    "allowedCidrs": {
      "granitValidator": "Validation:InvalidCidrNotation"
    },
    "expiresAt": {
      "format": "date-time",
      "granitValidator": "Validation:ExpirationMustBeFuture"
    },
    "cacheBehavior": {}
  },
  "ApiKeyUpdateScopesRequest": {
    "permissions": {
      "required": true,
      "granitValidator": "Validation:MaxPermissions"
    },
    "allowedCidrs": {
      "required": true,
      "granitValidator": "Validation:InvalidCidrNotation"
    }
  }
} satisfies Record<string, SchemaConstraints>;
