import { toEntityId, toISODateString } from '@granit/types';

import type { InvoiceLineItemResponse, InvoiceResponse } from '@granit/invoicing';
import type { Mutable } from '@granit/testing';

export const sampleInvoiceLineItems: Mutable<InvoiceLineItemResponse>[] = [
  {
    id: toEntityId<'InvoiceLineItem'>('li_001'),
    description: 'Pro Plan - Monthly subscription',
    quantity: 1,
    unitPrice: 4900,
    amount: 4900,
    taxRate: 21,
    taxAmount: 1029,
    sourceType: 'Subscription',
    sourceId: null,
    periodStart: toISODateString('2026-03-01T00:00:00Z'),
    periodEnd: toISODateString('2026-03-31T23:59:59Z'),
  },
  {
    id: toEntityId<'InvoiceLineItem'>('li_002'),
    description: 'Additional API calls (10,000)',
    quantity: 10,
    unitPrice: 100,
    amount: 1000,
    taxRate: 21,
    taxAmount: 210,
    sourceType: 'Subscription',
    sourceId: null,
    periodStart: toISODateString('2026-03-01T00:00:00Z'),
    periodEnd: toISODateString('2026-03-31T23:59:59Z'),
  },
];

export const sampleInvoices: Mutable<InvoiceResponse>[] = [
  {
    id: toEntityId<'Invoice'>('inv_001'),
    invoiceNumber: 'INV-2026-0001',
    status: 'Paid',
    documentType: 'Invoice',
    currency: 'EUR',
    subtotal: 5900,
    taxTotal: 1239,
    total: 7139,
    amountPaid: 7139,
    amountCredited: 0,
    amountRemaining: 0,
    parentInvoiceId: null,
    creditNoteReason: null,
    issuedAt: toISODateString('2026-03-01T00:00:00Z'),
    dueAt: toISODateString('2026-03-31T00:00:00Z'),
    paidAt: toISODateString('2026-03-15T10:00:00Z'),
    periodStart: toISODateString('2026-03-01T00:00:00Z'),
    periodEnd: toISODateString('2026-03-31T23:59:59Z'),
    collectionMethod: 'ChargeAutomatically',
    billingReason: 'SubscriptionCycle',
    lineItems: sampleInvoiceLineItems,
  },
  {
    id: toEntityId<'Invoice'>('inv_002'),
    invoiceNumber: 'INV-2026-0002',
    status: 'Open',
    documentType: 'Invoice',
    currency: 'EUR',
    subtotal: 9900,
    taxTotal: 2079,
    total: 11979,
    amountPaid: 0,
    amountCredited: 0,
    amountRemaining: 11979,
    parentInvoiceId: null,
    creditNoteReason: null,
    issuedAt: toISODateString('2026-04-01T00:00:00Z'),
    dueAt: toISODateString('2026-04-30T00:00:00Z'),
    paidAt: null,
    periodStart: toISODateString('2026-04-01T00:00:00Z'),
    periodEnd: toISODateString('2026-04-30T23:59:59Z'),
    collectionMethod: 'SendInvoice',
    billingReason: 'SubscriptionCycle',
    lineItems: [],
  },
  {
    id: toEntityId<'Invoice'>('inv_003'),
    invoiceNumber: 'INV-2026-0003',
    status: 'Draft',
    documentType: 'Invoice',
    currency: 'USD',
    subtotal: 19900,
    taxTotal: 0,
    total: 19900,
    amountPaid: 0,
    amountCredited: 0,
    amountRemaining: 19900,
    parentInvoiceId: null,
    creditNoteReason: null,
    issuedAt: null,
    dueAt: null,
    paidAt: null,
    periodStart: null,
    periodEnd: null,
    collectionMethod: 'ChargeAutomatically',
    billingReason: 'Manual',
    lineItems: [],
  },
  {
    id: toEntityId<'Invoice'>('inv_004'),
    invoiceNumber: 'CN-2026-0001',
    status: 'Cancelled',
    documentType: 'CreditNote',
    currency: 'EUR',
    subtotal: -2000,
    taxTotal: -420,
    total: -2420,
    amountPaid: 0,
    amountCredited: 0,
    amountRemaining: 0,
    parentInvoiceId: toEntityId<'Invoice'>('inv_001'),
    creditNoteReason: 'Adjustment',
    issuedAt: toISODateString('2026-03-20T00:00:00Z'),
    dueAt: null,
    paidAt: null,
    periodStart: null,
    periodEnd: null,
    collectionMethod: 'ChargeAutomatically',
    billingReason: 'Manual',
    lineItems: [],
  },
];
