// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/payments.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const paymentsConstraints = {
  "PaymentAttachMethodRequest": {
    "providerName": {
      "required": true,
      "maxLength": 50
    },
    "type": {
      "required": true,
      "maxLength": 50
    },
    "token": {
      "required": true,
      "maxLength": 500
    }
  },
  "PaymentChargeRequest": {
    "invoiceId": {
      "required": true,
      "format": "uuid"
    },
    "partyId": {
      "required": true,
      "format": "uuid"
    },
    "amount": {
      "required": true,
      "pattern": "^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$",
      "format": "double",
      "maximum": 999999999.99,
      "exclusiveMinimum": 0
    },
    "currency": {
      "required": true,
      "pattern": "^[A-Z]{3}$"
    },
    "methodType": {
      "required": true,
      "maxLength": 50
    },
    "providerName": {
      "maxLength": 50
    }
  },
  "PaymentCheckoutRequest": {
    "transactionId": {
      "required": true,
      "format": "uuid"
    },
    "amount": {
      "required": true,
      "pattern": "^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$",
      "format": "double",
      "maximum": 999999999.99,
      "exclusiveMinimum": 0
    },
    "currency": {
      "required": true,
      "pattern": "^[A-Z]{3}$"
    },
    "methodType": {
      "required": true,
      "maxLength": 50
    },
    "successUrl": {
      "required": true,
      "maxLength": 2048,
      "granitValidator": "Validation:Format:UrlHttps"
    },
    "cancelUrl": {
      "required": true,
      "maxLength": 2048,
      "granitValidator": "Validation:Format:UrlHttps"
    },
    "providerName": {
      "maxLength": 50
    }
  },
  "PaymentRefundRequest": {
    "transactionId": {
      "required": true,
      "format": "uuid"
    },
    "amount": {
      "required": true,
      "pattern": "^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$",
      "format": "double",
      "maximum": 999999999.99,
      "exclusiveMinimum": 0
    },
    "reason": {
      "maxLength": 500
    }
  }
} satisfies Record<string, SchemaConstraints>;
