// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/templating.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const templatingConstraints = {
  "SaveTemplateCategoryRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "description": {
      "maxLength": 500
    },
    "icon": {
      "maxLength": 100
    },
    "sortOrder": {
      "format": "int32"
    }
  },
  "SaveTemplateRequest": {
    "content": {
      "required": true,
      "maxLength": 1048576
    },
    "name": {
      "maxLength": 200,
      "pattern": "^[A-Za-z][A-Za-z0-9]*(\\.[A-Za-z][A-Za-z0-9]*)+$"
    },
    "culture": {
      "maxLength": 10,
      "pattern": "^[a-zA-Z]{2,8}(-[a-zA-Z0-9]{1,8})*$"
    },
    "mimeType": {
      "required": true,
      "maxLength": 127,
      "granitValidator": "Validation:UnsupportedMimeType"
    },
    "layoutName": {},
    "concurrencyStamp": {}
  },
  "TemplatePreviewRequest": {
    "culture": {
      "maxLength": 10,
      "pattern": "^[a-zA-Z]{2,8}(-[a-zA-Z0-9]{1,8})*$"
    },
    "data": {}
  }
} satisfies Record<string, SchemaConstraints>;
