// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/openiddict.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const openiddictConstraints = {
  "AdminOidcCreateApplicationRequest": {
    "clientId": {
      "required": true,
      "maxLength": 256
    },
    "displayName": {
      "maxLength": 256
    },
    "clientSecret": {},
    "type": {},
    "permissions": {
      "maxLength": 512
    },
    "redirectUris": {
      "granitValidator": "Validation:Format:AbsoluteUri"
    },
    "postLogoutRedirectUris": {
      "granitValidator": "Validation:Format:AbsoluteUri"
    },
    "consentType": {
      "maxLength": 64
    },
    "signingKeyJwk": {
      "maxLength": 65536
    },
    "clientSide": {},
    "deviceKind": {},
    "tenantId": {
      "format": "uuid"
    },
    "generateClientSecret": {}
  },
  "AdminOidcCreateAuthorizationRequest": {
    "subject": {
      "required": true,
      "maxLength": 256
    },
    "clientId": {
      "required": true,
      "maxLength": 256
    },
    "scopes": {
      "required": true
    }
  },
  "AdminOidcCreateScopeRequest": {
    "name": {
      "required": true,
      "maxLength": 256
    },
    "displayName": {
      "maxLength": 256
    },
    "description": {
      "maxLength": 1024
    },
    "resources": {
      "maxLength": 512
    },
    "tenantId": {
      "format": "uuid"
    }
  },
  "AdminOidcUpdateApplicationRequest": {
    "displayName": {
      "maxLength": 256
    },
    "type": {},
    "permissions": {
      "maxLength": 512
    },
    "redirectUris": {
      "granitValidator": "Validation:Format:AbsoluteUri"
    },
    "postLogoutRedirectUris": {
      "granitValidator": "Validation:Format:AbsoluteUri"
    },
    "consentType": {
      "maxLength": 64
    },
    "signingKeyJwk": {
      "maxLength": 65536
    },
    "clientSide": {},
    "deviceKind": {}
  },
  "AdminOidcUpdateScopeRequest": {
    "displayName": {
      "maxLength": 256
    },
    "description": {
      "maxLength": 1024
    },
    "resources": {
      "maxLength": 512
    }
  }
} satisfies Record<string, SchemaConstraints>;
