// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/hostnames.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const hostnamesConstraints = {
  "CreateManagedHostnameRequest": {
    "host": {
      "required": true,
      "maxLength": 253
    },
    "ownerType": {
      "required": true,
      "maxLength": 100
    },
    "ownerId": {
      "required": true,
      "format": "uuid"
    },
    "tenantId": {
      "format": "uuid"
    },
    "isPrimary": {}
  },
  "ReportCertificateStatusRequest": {
    "status": {
      "required": true
    },
    "expiresAt": {
      "format": "date-time"
    }
  }
} satisfies Record<string, SchemaConstraints>;
