export type Continent = 'Africa' | 'Americas' | 'Asia' | 'Europe' | 'Oceania' | 'Antarctica';

/**
 * ISO 3166-1 alpha-2 → continent. Aligned with the UN M49 region codes
 * collapsed to six continents (Antarctica kept separate; "Americas" merges
 * North and South). Source-of-truth: UNSD M49 (May 2024 revision).
 *
 * Used by the `<PhoneInput>` country picker to surface a continental section
 * heading. Countries / territories absent here fall back to "Other" (e.g. a
 * future ISO addition shipped by libphonenumber-js before this list catches
 * up — preferable to a build break).
 */
export const COUNTRY_TO_CONTINENT: Readonly<Record<string, Continent>> = {
  // Africa
  DZ: 'Africa',
  AO: 'Africa',
  BJ: 'Africa',
  BW: 'Africa',
  BF: 'Africa',
  BI: 'Africa',
  CV: 'Africa',
  CM: 'Africa',
  CF: 'Africa',
  TD: 'Africa',
  KM: 'Africa',
  CG: 'Africa',
  CD: 'Africa',
  CI: 'Africa',
  DJ: 'Africa',
  EG: 'Africa',
  GQ: 'Africa',
  ER: 'Africa',
  SZ: 'Africa',
  ET: 'Africa',
  GA: 'Africa',
  GM: 'Africa',
  GH: 'Africa',
  GN: 'Africa',
  GW: 'Africa',
  KE: 'Africa',
  LS: 'Africa',
  LR: 'Africa',
  LY: 'Africa',
  MG: 'Africa',
  MW: 'Africa',
  ML: 'Africa',
  MR: 'Africa',
  MU: 'Africa',
  YT: 'Africa',
  MA: 'Africa',
  MZ: 'Africa',
  NA: 'Africa',
  NE: 'Africa',
  NG: 'Africa',
  RE: 'Africa',
  RW: 'Africa',
  SH: 'Africa',
  ST: 'Africa',
  SN: 'Africa',
  SC: 'Africa',
  SL: 'Africa',
  SO: 'Africa',
  ZA: 'Africa',
  SS: 'Africa',
  SD: 'Africa',
  TZ: 'Africa',
  TG: 'Africa',
  TN: 'Africa',
  UG: 'Africa',
  EH: 'Africa',
  ZM: 'Africa',
  ZW: 'Africa',

  // Americas
  AI: 'Americas',
  AG: 'Americas',
  AR: 'Americas',
  AW: 'Americas',
  BS: 'Americas',
  BB: 'Americas',
  BZ: 'Americas',
  BM: 'Americas',
  BO: 'Americas',
  BQ: 'Americas',
  BR: 'Americas',
  CA: 'Americas',
  KY: 'Americas',
  CL: 'Americas',
  CO: 'Americas',
  CR: 'Americas',
  CU: 'Americas',
  CW: 'Americas',
  DM: 'Americas',
  DO: 'Americas',
  EC: 'Americas',
  SV: 'Americas',
  FK: 'Americas',
  GF: 'Americas',
  GL: 'Americas',
  GD: 'Americas',
  GP: 'Americas',
  GT: 'Americas',
  GY: 'Americas',
  HT: 'Americas',
  HN: 'Americas',
  JM: 'Americas',
  MQ: 'Americas',
  MX: 'Americas',
  MS: 'Americas',
  NI: 'Americas',
  PA: 'Americas',
  PY: 'Americas',
  PE: 'Americas',
  PR: 'Americas',
  BL: 'Americas',
  KN: 'Americas',
  LC: 'Americas',
  MF: 'Americas',
  PM: 'Americas',
  VC: 'Americas',
  SR: 'Americas',
  TT: 'Americas',
  TC: 'Americas',
  US: 'Americas',
  UY: 'Americas',
  VE: 'Americas',
  VG: 'Americas',
  VI: 'Americas',

  // Asia
  AF: 'Asia',
  AM: 'Asia',
  AZ: 'Asia',
  BH: 'Asia',
  BD: 'Asia',
  BT: 'Asia',
  BN: 'Asia',
  KH: 'Asia',
  CN: 'Asia',
  CY: 'Asia',
  GE: 'Asia',
  HK: 'Asia',
  IN: 'Asia',
  ID: 'Asia',
  IR: 'Asia',
  IQ: 'Asia',
  IL: 'Asia',
  JP: 'Asia',
  JO: 'Asia',
  KZ: 'Asia',
  KW: 'Asia',
  KG: 'Asia',
  LA: 'Asia',
  LB: 'Asia',
  MO: 'Asia',
  MY: 'Asia',
  MV: 'Asia',
  MN: 'Asia',
  MM: 'Asia',
  NP: 'Asia',
  KP: 'Asia',
  OM: 'Asia',
  PK: 'Asia',
  PS: 'Asia',
  PH: 'Asia',
  QA: 'Asia',
  SA: 'Asia',
  SG: 'Asia',
  KR: 'Asia',
  LK: 'Asia',
  SY: 'Asia',
  TW: 'Asia',
  TJ: 'Asia',
  TH: 'Asia',
  TL: 'Asia',
  TR: 'Asia',
  TM: 'Asia',
  AE: 'Asia',
  UZ: 'Asia',
  VN: 'Asia',
  YE: 'Asia',

  // Europe
  AX: 'Europe',
  AL: 'Europe',
  AD: 'Europe',
  AT: 'Europe',
  BY: 'Europe',
  BE: 'Europe',
  BA: 'Europe',
  BG: 'Europe',
  HR: 'Europe',
  CZ: 'Europe',
  DK: 'Europe',
  EE: 'Europe',
  FO: 'Europe',
  FI: 'Europe',
  FR: 'Europe',
  DE: 'Europe',
  GI: 'Europe',
  GR: 'Europe',
  GG: 'Europe',
  VA: 'Europe',
  HU: 'Europe',
  IS: 'Europe',
  IE: 'Europe',
  IM: 'Europe',
  IT: 'Europe',
  JE: 'Europe',
  XK: 'Europe',
  LV: 'Europe',
  LI: 'Europe',
  LT: 'Europe',
  LU: 'Europe',
  MT: 'Europe',
  MD: 'Europe',
  MC: 'Europe',
  ME: 'Europe',
  NL: 'Europe',
  MK: 'Europe',
  NO: 'Europe',
  PL: 'Europe',
  PT: 'Europe',
  RO: 'Europe',
  RU: 'Europe',
  SM: 'Europe',
  RS: 'Europe',
  SK: 'Europe',
  SI: 'Europe',
  ES: 'Europe',
  SJ: 'Europe',
  SE: 'Europe',
  CH: 'Europe',
  UA: 'Europe',
  GB: 'Europe',

  // Oceania
  AS: 'Oceania',
  AU: 'Oceania',
  CX: 'Oceania',
  CC: 'Oceania',
  CK: 'Oceania',
  FJ: 'Oceania',
  PF: 'Oceania',
  GU: 'Oceania',
  KI: 'Oceania',
  MH: 'Oceania',
  FM: 'Oceania',
  NR: 'Oceania',
  NC: 'Oceania',
  NZ: 'Oceania',
  NU: 'Oceania',
  NF: 'Oceania',
  MP: 'Oceania',
  PW: 'Oceania',
  PG: 'Oceania',
  PN: 'Oceania',
  WS: 'Oceania',
  SB: 'Oceania',
  TK: 'Oceania',
  TO: 'Oceania',
  TV: 'Oceania',
  UM: 'Oceania',
  VU: 'Oceania',
  WF: 'Oceania',

  // Antarctica
  AQ: 'Antarctica',
  BV: 'Antarctica',
  TF: 'Antarctica',
  HM: 'Antarctica',
  GS: 'Antarctica',
};

export const CONTINENT_ORDER: readonly Continent[] = [
  'Europe',
  'Africa',
  'Americas',
  'Asia',
  'Oceania',
  'Antarctica',
];
