import { toEntityId, toISODateString } from '@granit/types';
import { WebhookSubscriptionStatus } from '@granit/webhooks';

import type {
  WebhookDeliveryAttemptResponse,
  WebhookModuleConfig,
  WebhookSubscriptionResponse,
  WebhookSubscriptionStatsResponse,
} from '@granit/webhooks';

export const mockWebhookSubscriptions: WebhookSubscriptionResponse[] = [
  {
    id: toEntityId<'WebhookSubscription'>('ws-1'),
    targetUrl: 'https://api.partner-health.be/webhooks/patients',
    eventType: 'patient.created',
    status: WebhookSubscriptionStatus.Active,
    consecutiveFailureCount: 0,
    lastSuccessAt: toISODateString('2026-03-09T08:15:00Z'),
    createdAt: toISODateString('2025-11-10T09:00:00Z'),
    modifiedAt: toISODateString('2025-11-10T09:00:00Z'),
    signingSecretHint: 'whsec_b46a****************5182',
  },
  {
    id: toEntityId<'WebhookSubscription'>('ws-2'),
    targetUrl: 'https://erp.clinic-brussels.be/api/hooks/appointments',
    eventType: 'appointment.created',
    status: WebhookSubscriptionStatus.Active,
    consecutiveFailureCount: 0,
    lastSuccessAt: toISODateString('2026-03-09T07:45:00Z'),
    createdAt: toISODateString('2025-12-01T14:30:00Z'),
    modifiedAt: toISODateString('2025-12-01T14:30:00Z'),
    signingSecretHint: 'whsec_3f2c****************9d11',
  },
  {
    id: toEntityId<'WebhookSubscription'>('ws-3'),
    targetUrl: 'https://old-integration.example.com/webhook',
    eventType: 'patient.updated',
    status: WebhookSubscriptionStatus.Suspended,
    consecutiveFailureCount: 5,
    lastSuccessAt: toISODateString('2026-02-20T16:00:00Z'),
    createdAt: toISODateString('2025-10-05T11:00:00Z'),
    modifiedAt: toISODateString('2026-02-25T10:30:00Z'),
    signingSecretHint: 'whsec_7e88****************a4f0',
  },
  {
    id: toEntityId<'WebhookSubscription'>('ws-4'),
    targetUrl: 'https://notifications.granit-showcase.local/hooks/documents',
    eventType: 'document.uploaded',
    status: WebhookSubscriptionStatus.Active,
    consecutiveFailureCount: 1,
    lastSuccessAt: toISODateString('2026-03-08T22:10:00Z'),
    createdAt: toISODateString('2026-01-15T08:00:00Z'),
    modifiedAt: toISODateString('2026-01-15T08:00:00Z'),
    signingSecretHint: 'whsec_19ce****************6b73',
  },
  {
    // Legacy: created before the hint was introduced — UI falls back to placeholder.
    id: toEntityId<'WebhookSubscription'>('ws-5'),
    targetUrl: 'https://legacy.partner.com/v1/events',
    eventType: 'user.created',
    status: WebhookSubscriptionStatus.Deactivated,
    consecutiveFailureCount: 0,
    lastSuccessAt: toISODateString('2025-09-01T12:00:00Z'),
    createdAt: toISODateString('2025-06-01T10:00:00Z'),
    modifiedAt: toISODateString('2025-12-15T09:00:00Z'),
    signingSecretHint: null,
  },
  {
    id: toEntityId<'WebhookSubscription'>('ws-6'),
    targetUrl: 'https://analytics.granit-showcase.local/ingest/appointments',
    eventType: 'appointment.cancelled',
    status: WebhookSubscriptionStatus.Active,
    consecutiveFailureCount: 0,
    lastSuccessAt: toISODateString('2026-03-09T09:00:00Z'),
    createdAt: toISODateString('2026-02-01T16:00:00Z'),
    modifiedAt: toISODateString('2026-02-01T16:00:00Z'),
    signingSecretHint: 'whsec_5a4d****************0e2f',
  },
  {
    id: toEntityId<'WebhookSubscription'>('ws-7'),
    targetUrl: 'https://archive.clinic-brussels.be/hooks/documents',
    eventType: 'document.signed',
    status: WebhookSubscriptionStatus.Suspended,
    consecutiveFailureCount: 3,
    lastSuccessAt: toISODateString('2026-03-01T14:00:00Z'),
    createdAt: toISODateString('2026-01-20T10:00:00Z'),
    modifiedAt: toISODateString('2026-03-05T08:00:00Z'),
    signingSecretHint: 'whsec_c2b1****************8a90',
  },
];

export const mockWebhookDeliveryAttempts: WebhookDeliveryAttemptResponse[] = [
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-1'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-1'),
    tenantId: null,
    eventType: 'patient.created',
    targetUrl: 'https://api.partner-health.be/webhooks/patients',
    httpStatusCode: 200,
    payloadHash: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
    occurredAt: toISODateString('2026-03-09T08:15:00Z'),
    durationMs: 145,
    errorMessage: null,
    isSuccess: true,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-2'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-1'),
    tenantId: null,
    eventType: 'patient.created',
    targetUrl: 'https://api.partner-health.be/webhooks/patients',
    httpStatusCode: 200,
    payloadHash: 'b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3',
    occurredAt: toISODateString('2026-03-08T14:30:00Z'),
    durationMs: 230,
    errorMessage: null,
    isSuccess: true,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-3'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-3'),
    tenantId: null,
    eventType: 'patient.updated',
    targetUrl: 'https://old-integration.example.com/webhook',
    httpStatusCode: 500,
    payloadHash: 'c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
    occurredAt: toISODateString('2026-02-25T10:30:00Z'),
    durationMs: 2050,
    errorMessage: 'Internal Server Error',
    isSuccess: false,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-4'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-3'),
    tenantId: null,
    eventType: 'patient.updated',
    targetUrl: 'https://old-integration.example.com/webhook',
    httpStatusCode: 500,
    payloadHash: 'd4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5',
    occurredAt: toISODateString('2026-02-25T09:00:00Z'),
    durationMs: 1800,
    errorMessage: 'Internal Server Error',
    isSuccess: false,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-5'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-3'),
    tenantId: null,
    eventType: 'patient.updated',
    targetUrl: 'https://old-integration.example.com/webhook',
    httpStatusCode: null,
    payloadHash: 'e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6',
    occurredAt: toISODateString('2026-02-24T16:00:00Z'),
    durationMs: 10000,
    errorMessage: 'Request timeout after 10000ms',
    isSuccess: false,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-6'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-3'),
    tenantId: null,
    eventType: 'patient.updated',
    targetUrl: 'https://old-integration.example.com/webhook',
    httpStatusCode: 503,
    payloadHash: 'f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1',
    occurredAt: toISODateString('2026-02-24T12:00:00Z'),
    durationMs: 350,
    errorMessage: 'Service Unavailable',
    isSuccess: false,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-7'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-3'),
    tenantId: null,
    eventType: 'patient.updated',
    targetUrl: 'https://old-integration.example.com/webhook',
    httpStatusCode: 200,
    payloadHash: 'a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8',
    occurredAt: toISODateString('2026-02-20T16:00:00Z'),
    durationMs: 180,
    errorMessage: null,
    isSuccess: true,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-8'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-4'),
    tenantId: null,
    eventType: 'document.uploaded',
    targetUrl: 'https://notifications.granit-showcase.local/hooks/documents',
    httpStatusCode: 200,
    payloadHash: 'b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9',
    occurredAt: toISODateString('2026-03-08T22:10:00Z'),
    durationMs: 95,
    errorMessage: null,
    isSuccess: true,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-9'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-4'),
    tenantId: null,
    eventType: 'document.uploaded',
    targetUrl: 'https://notifications.granit-showcase.local/hooks/documents',
    httpStatusCode: 502,
    payloadHash: 'c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0',
    occurredAt: toISODateString('2026-03-08T18:30:00Z'),
    durationMs: 450,
    errorMessage: 'Bad Gateway',
    isSuccess: false,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-10'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-2'),
    tenantId: null,
    eventType: 'appointment.created',
    targetUrl: 'https://erp.clinic-brussels.be/api/hooks/appointments',
    httpStatusCode: 200,
    payloadHash: 'd0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1',
    occurredAt: toISODateString('2026-03-09T07:45:00Z'),
    durationMs: 320,
    errorMessage: null,
    isSuccess: true,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-11'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-6'),
    tenantId: null,
    eventType: 'appointment.cancelled',
    targetUrl: 'https://analytics.granit-showcase.local/ingest/appointments',
    httpStatusCode: 200,
    payloadHash: 'e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2',
    occurredAt: toISODateString('2026-03-09T09:00:00Z'),
    durationMs: 75,
    errorMessage: null,
    isSuccess: true,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-12'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-7'),
    tenantId: null,
    eventType: 'document.signed',
    targetUrl: 'https://archive.clinic-brussels.be/hooks/documents',
    httpStatusCode: 403,
    payloadHash: 'f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7b8c9d0e1f2a7',
    occurredAt: toISODateString('2026-03-05T08:00:00Z'),
    durationMs: 120,
    errorMessage: 'Forbidden — API key expired',
    isSuccess: false,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-13'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-7'),
    tenantId: null,
    eventType: 'document.signed',
    targetUrl: 'https://archive.clinic-brussels.be/hooks/documents',
    httpStatusCode: 403,
    payloadHash: 'a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4',
    occurredAt: toISODateString('2026-03-04T15:00:00Z'),
    durationMs: 110,
    errorMessage: 'Forbidden — API key expired',
    isSuccess: false,
    payload: null,
  },
  {
    deliveryId: toEntityId<'WebhookDelivery'>('del-14'),
    subscriptionId: toEntityId<'WebhookSubscription'>('ws-7'),
    tenantId: null,
    eventType: 'document.signed',
    targetUrl: 'https://archive.clinic-brussels.be/hooks/documents',
    httpStatusCode: 200,
    payloadHash: 'b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5d6e7f8a3b4c5',
    occurredAt: toISODateString('2026-03-01T14:00:00Z'),
    durationMs: 200,
    errorMessage: null,
    isSuccess: true,
    payload: null,
  },
];

export const mockWebhookStats: WebhookSubscriptionStatsResponse = {
  totalSubscriptions: 7,
  activeCount: 4,
  suspendedCount: 2,
  deactivatedCount: 1,
  deliveriesLast24h: 8,
  successRateLast24h: 87.5,
  avgResponseTimeMsLast24h: 185,
};

export const mockWebhookConfig: WebhookModuleConfig = {
  storePayload: false,
};
