// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/tax.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const taxConstraints = {
  "TaxValidateRequest": {
    "taxId": {
      "required": true,
      "maxLength": 30
    },
    "countryCode": {
      "required": true,
      "maxLength": 2,
      "minLength": 2
    }
  }
} satisfies Record<string, SchemaConstraints>;
