// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/cms.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const cmsConstraints = {
  "AddReleaseActionRequest": {
    "contentType": {
      "required": true,
      "maxLength": 100
    },
    "contentId": {
      "required": true,
      "format": "uuid"
    },
    "culture": {
      "required": true,
      "maxLength": 20
    },
    "type": {
      "required": true
    },
    "concurrencyStamp": {
      "required": true
    }
  },
  "BlockDataResolveRequest": {
    "dataSourceKey": {
      "required": true,
      "maxLength": 256
    },
    "query": {
      "required": true,
      "maxLength": 10000
    },
    "siteId": {
      "required": true,
      "format": "uuid"
    },
    "culture": {
      "required": true,
      "maxLength": 20
    }
  },
  "CreatePageRequest": {
    "parentId": {
      "required": true,
      "format": "uuid"
    },
    "slugSegment": {
      "required": true,
      "maxLength": 200,
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
    },
    "layoutKey": {
      "required": true,
      "maxLength": 100,
      "pattern": "^[a-z0-9]+([._-][a-z0-9]+)*$"
    }
  },
  "CreateReleaseRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    }
  },
  "CreateSiteRequest": {
    "slug": {
      "required": true,
      "maxLength": 200,
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
    },
    "defaultCulture": {
      "required": true,
      "maxLength": 20
    },
    "allowedCultures": {
      "required": true
    },
    "domains": {},
    "defaultTheme": {}
  },
  "MenuCreateRequest": {
    "siteId": {
      "required": true,
      "format": "uuid"
    },
    "key": {
      "required": true,
      "maxLength": 100,
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
    },
    "title": {
      "required": true,
      "maxLength": 200
    },
    "items": {}
  },
  "MenuItemRequest": {
    "label": {
      "required": true,
      "maxLength": 200
    },
    "kind": {
      "required": true
    },
    "pageId": {
      "format": "uuid"
    },
    "url": {},
    "anchor": {},
    "isVisible": {},
    "icon": {},
    "cssClass": {},
    "children": {}
  },
  "MenuUpdateRequest": {
    "title": {
      "required": true,
      "maxLength": 200
    },
    "items": {
      "required": true
    }
  },
  "MintPreviewTokenRequest": {
    "culture": {
      "required": true
    },
    "lifetimeSeconds": {
      "required": true,
      "format": "int32"
    }
  },
  "MovePageRequest": {
    "newParentId": {
      "required": true,
      "format": "uuid"
    },
    "concurrencyStamp": {
      "required": true
    }
  },
  "RenamePageRequest": {
    "slugSegment": {
      "required": true,
      "maxLength": 200,
      "pattern": "^[a-z0-9]+(-[a-z0-9]+)*$"
    },
    "concurrencyStamp": {
      "required": true
    }
  },
  "RenameReleaseRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "concurrencyStamp": {
      "required": true
    }
  },
  "SaveDraftContentRequest": {
    "contentJson": {
      "required": true,
      "maxLength": 2097152
    },
    "title": {
      "required": true,
      "maxLength": 500
    }
  },
  "ScheduleReleaseRequest": {
    "localDateTime": {
      "required": true,
      "format": "date-time"
    },
    "timeZoneId": {
      "required": true,
      "maxLength": 64
    },
    "concurrencyStamp": {
      "required": true
    }
  },
  "SetPageTranslationRequest": {
    "urlSlug": {
      "required": true
    },
    "title": {
      "required": true,
      "maxLength": 500
    }
  },
  "SetSiteHomePageRequest": {
    "pageId": {
      "required": true,
      "format": "uuid"
    }
  },
  "UpdateSiteRequest": {
    "defaultCulture": {
      "required": true,
      "maxLength": 20
    },
    "allowedCultures": {
      "required": true
    },
    "domains": {
      "required": true
    },
    "defaultTheme": {
      "required": true,
      "maxLength": 100
    },
    "activated": {
      "required": true
    }
  }
} satisfies Record<string, SchemaConstraints>;
