/**
 * Metadata about a single exportable field.
 * Mirrors `Granit.DataExchange.Endpoints.Dtos.Export.ExportFieldResponse`.
 */
export interface ExportFieldResponse {
  readonly propertyPath: string;
  readonly clrTypeName: string;
  readonly header: string | null;
  readonly format: string | null;
  readonly order: number;
  readonly isNavigation: boolean;
}

/**
 * @deprecated Renamed to {@link ExportFieldResponse} to mirror the .NET DTO name. Will be removed in a future release.
 */
export type ExportField = ExportFieldResponse;

/**
 * Summary of a registered export definition.
 * Mirrors `Granit.DataExchange.Endpoints.Dtos.Export.ExportDefinitionResponse`.
 */
export interface ExportDefinitionResponse {
  readonly name: string;
  readonly entityType: string;
  readonly supportedFormats: readonly string[];
  /** Whether this definition was auto-generated by the framework (vs. explicitly registered). */
  readonly isAutoGenerated: boolean;
}
