export { DocumentsExplorerPage } from './components/documents-explorer-page';
export { DocumentDetailPage } from './components/document-detail-page';
export { DocumentPropertiesPage } from './components/document-properties-page';
export { DocumentPublicLinksPage } from './components/document-public-links-page';
export { DocumentRenditionsPage } from './components/document-renditions-page';
export { DocumentResolutionPage } from './components/document-resolution-page';
export { TrashBinPage } from './components/trash-bin-page';
export { StorageQuotaPage } from './components/storage-quota-page';
export { DOCUMENTS_PERMISSIONS } from './constants';
export { documentsAdminTranslationsEn, documentsAdminTranslationsFr } from './locales';
