// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/cms-redirects.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const cmsRedirectsConstraints = {
  "RedirectCreateRequest": {
    "source": {
      "required": true,
      "maxLength": 2048,
      "pattern": "^/"
    },
    "target": {
      "required": true,
      "maxLength": 2048,
      "pattern": "^(https?://|/)"
    },
    "type": {},
    "matchType": {},
    "culture": {
      "maxLength": 20
    },
    "isActive": {}
  },
  "RedirectUpdateRequest": {
    "target": {
      "required": true,
      "maxLength": 2048,
      "pattern": "^(https?://|/)"
    },
    "type": {},
    "matchType": {},
    "isActive": {}
  },
  "SiteRedirectSettingsRequest": {
    "autoRedirectOnMove": {
      "required": true
    }
  }
} satisfies Record<string, SchemaConstraints>;
