import { toEntityId, toISODateString } from '@granit/types';

import type { IdentityDeviceActivity, IdentitySession, IdentityUser } from '@granit/identity';

export const mockUsers: IdentityUser[] = [
  {
    userId: toEntityId<'User'>('d2c47314-4d08-4952-98b1-a1b8a6e22ef1'),
    email: 'marie.dupont@granit-showcase.local',
    firstName: 'Marie',
    lastName: 'Dupont',
    username: 'marie.dupont',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-002'),
    email: 'jean.martin@granit-showcase.local',
    firstName: 'Jean',
    lastName: 'Martin',
    username: 'jean.martin',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-003'),
    email: 'sophie.bernard@granit-showcase.local',
    firstName: 'Sophie',
    lastName: 'Bernard',
    username: 'sophie.bernard',
    enabled: false,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-004'),
    email: 'pierre.leblanc@granit-showcase.local',
    firstName: 'Pierre',
    lastName: 'Leblanc',
    username: 'pierre.leblanc',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-005'),
    email: 'claire.moreau@granit-showcase.local',
    firstName: 'Claire',
    lastName: 'Moreau',
    username: 'claire.moreau',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-006'),
    email: 'thomas.petit@granit-showcase.local',
    firstName: 'Thomas',
    lastName: 'Petit',
    username: 'thomas.petit',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-007'),
    email: 'alice.robert@granit-showcase.local',
    firstName: 'Alice',
    lastName: 'Robert',
    username: 'alice.robert',
    enabled: false,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-008'),
    email: 'paul.simon@granit-showcase.local',
    firstName: 'Paul',
    lastName: 'Simon',
    username: 'paul.simon',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-009'),
    email: 'nathalie.garcia@granit-showcase.local',
    firstName: 'Nathalie',
    lastName: 'Garcia',
    username: 'nathalie.garcia',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-010'),
    email: 'francois.lambert@granit-showcase.local',
    firstName: 'François',
    lastName: 'Lambert',
    username: 'francois.lambert',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-011'),
    email: 'isabelle.rousseau@granit-showcase.local',
    firstName: 'Isabelle',
    lastName: 'Rousseau',
    username: 'isabelle.rousseau',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-012'),
    email: 'marc.fournier@granit-showcase.local',
    firstName: 'Marc',
    lastName: 'Fournier',
    username: 'marc.fournier',
    enabled: false,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-013'),
    email: 'valerie.girard@granit-showcase.local',
    firstName: 'Valérie',
    lastName: 'Girard',
    username: 'valerie.girard',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-014'),
    email: 'luc.bonnet@granit-showcase.local',
    firstName: 'Luc',
    lastName: 'Bonnet',
    username: 'luc.bonnet',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-015'),
    email: 'emilie.dupuis@granit-showcase.local',
    firstName: 'Émilie',
    lastName: 'Dupuis',
    username: 'emilie.dupuis',
    enabled: true,
    metadata: {},
  },
];

export const mockSessions: IdentitySession[] = [
  {
    sessionId: toEntityId<'IdentitySession'>('sess-abc-001'),
    ipAddress: '10.0.1.42',
    startedAt: toISODateString('2026-03-06T08:00:00Z'),
    lastAccess: toISODateString('2026-03-06T09:30:00Z'),
    rememberMe: false,
    clients: ['granit-showcase-admin', 'granit-showcase-app'],
    location: {
      city: 'Brussels',
      region: 'Brussels-Capital',
      country: 'Belgium',
      countryCode: 'BE',
      latitude: 50.8503,
      longitude: 4.3517,
    },
    riskLevel: 'None',
  },
  {
    sessionId: toEntityId<'IdentitySession'>('sess-abc-002'),
    ipAddress: '10.0.1.42',
    startedAt: toISODateString('2026-03-05T18:00:00Z'),
    lastAccess: toISODateString('2026-03-05T20:15:00Z'),
    rememberMe: true,
    clients: ['granit-showcase-app'],
    location: null,
    riskLevel: 'Low',
  },
];

export const mockDevices: IdentityDeviceActivity[] = [
  {
    ipAddress: '10.0.1.42',
    lastAccess: toISODateString('2026-03-06T09:30:00Z'),
    device: 'Desktop',
    os: 'Windows',
    osVersion: '11',
    browser: 'Chrome/122.0',
    mobile: false,
    current: true,
    sessions: mockSessions,
    location: {
      city: 'Brussels',
      region: 'Brussels-Capital',
      country: 'Belgium',
      countryCode: 'BE',
      latitude: 50.8503,
      longitude: 4.3517,
    },
  },
  {
    ipAddress: '10.0.1.55',
    lastAccess: toISODateString('2026-03-04T12:00:00Z'),
    device: 'Mobile',
    os: 'iOS',
    osVersion: '17',
    browser: 'Safari/17.0',
    mobile: true,
    current: false,
    sessions: [],
    location: null,
  },
];

export const mockPasswordChangedAt: Record<string, string | null> = {
  'd2c47314-4d08-4952-98b1-a1b8a6e22ef1': '2026-01-15T10:00:00Z',
  'user-002': '2025-11-20T14:30:00Z',
  'user-003': null,
  'user-004': null,
};
