import { toEntityId, toISODateString } from '@granit/types';

import type { IdentityUser, UserDeviceResponse, UserSessionResponse } from '@granit/identity';

export const mockUsers: IdentityUser[] = [
  {
    userId: toEntityId<'User'>('d2c47314-4d08-4952-98b1-a1b8a6e22ef1'),
    email: 'marie.dupont@granit-showcase.local',
    firstName: 'Marie',
    lastName: 'Dupont',
    username: 'marie.dupont',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-002'),
    email: 'jean.martin@granit-showcase.local',
    firstName: 'Jean',
    lastName: 'Martin',
    username: 'jean.martin',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-003'),
    email: 'sophie.bernard@granit-showcase.local',
    firstName: 'Sophie',
    lastName: 'Bernard',
    username: 'sophie.bernard',
    enabled: false,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-004'),
    email: 'pierre.leblanc@granit-showcase.local',
    firstName: 'Pierre',
    lastName: 'Leblanc',
    username: 'pierre.leblanc',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-005'),
    email: 'claire.moreau@granit-showcase.local',
    firstName: 'Claire',
    lastName: 'Moreau',
    username: 'claire.moreau',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-006'),
    email: 'thomas.petit@granit-showcase.local',
    firstName: 'Thomas',
    lastName: 'Petit',
    username: 'thomas.petit',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-007'),
    email: 'alice.robert@granit-showcase.local',
    firstName: 'Alice',
    lastName: 'Robert',
    username: 'alice.robert',
    enabled: false,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-008'),
    email: 'paul.simon@granit-showcase.local',
    firstName: 'Paul',
    lastName: 'Simon',
    username: 'paul.simon',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-009'),
    email: 'nathalie.garcia@granit-showcase.local',
    firstName: 'Nathalie',
    lastName: 'Garcia',
    username: 'nathalie.garcia',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-010'),
    email: 'francois.lambert@granit-showcase.local',
    firstName: 'François',
    lastName: 'Lambert',
    username: 'francois.lambert',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-011'),
    email: 'isabelle.rousseau@granit-showcase.local',
    firstName: 'Isabelle',
    lastName: 'Rousseau',
    username: 'isabelle.rousseau',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-012'),
    email: 'marc.fournier@granit-showcase.local',
    firstName: 'Marc',
    lastName: 'Fournier',
    username: 'marc.fournier',
    enabled: false,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-013'),
    email: 'valerie.girard@granit-showcase.local',
    firstName: 'Valérie',
    lastName: 'Girard',
    username: 'valerie.girard',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-014'),
    email: 'luc.bonnet@granit-showcase.local',
    firstName: 'Luc',
    lastName: 'Bonnet',
    username: 'luc.bonnet',
    enabled: true,
    metadata: {},
  },
  {
    userId: toEntityId<'User'>('user-015'),
    email: 'emilie.dupuis@granit-showcase.local',
    firstName: 'Émilie',
    lastName: 'Dupuis',
    username: 'emilie.dupuis',
    enabled: true,
    metadata: {},
  },
];

export const mockSessions: UserSessionResponse[] = [
  {
    sessionId: toEntityId<'UserSession'>('sess-abc-001'),
    isCurrent: true,
    createdAt: toISODateString('2026-03-06T08:00:00Z'),
    lastAccessedAt: toISODateString('2026-03-06T09:30:00Z'),
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/122.0',
    ipAddress: '10.0.1.0',
    location: {
      city: 'Brussels',
      region: 'Brussels-Capital',
      country: 'Belgium',
      countryCode: 'BE',
      latitude: 50.8503,
      longitude: 4.3517,
    },
    riskLevel: 'None',
    riskReasons: null,
  },
  {
    sessionId: toEntityId<'UserSession'>('sess-abc-002'),
    isCurrent: false,
    createdAt: toISODateString('2026-03-05T18:00:00Z'),
    lastAccessedAt: toISODateString('2026-03-05T20:15:00Z'),
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0) Safari/17.0',
    ipAddress: '10.0.1.0',
    location: null,
    riskLevel: 'Low',
    riskReasons: ['new_location'],
  },
];

export const mockDevices: UserDeviceResponse[] = [
  {
    deviceId: toEntityId<'UserDevice'>('dev-abc-001'),
    kind: 'Browser',
    operatingSystem: 'Windows',
    browser: 'Chrome',
    lastSeen: toISODateString('2026-03-06T09:30:00Z'),
    sessionCount: 2,
    isTrusted: false,
    trustedUntil: null,
    lastLocation: {
      city: 'Brussels',
      region: 'Brussels-Capital',
      country: 'Belgium',
      countryCode: 'BE',
      latitude: 50.8503,
      longitude: 4.3517,
    },
  },
  {
    deviceId: toEntityId<'UserDevice'>('dev-abc-002'),
    kind: 'MobileApp',
    operatingSystem: 'iOS',
    browser: null,
    lastSeen: toISODateString('2026-03-04T12:00:00Z'),
    sessionCount: 0,
    isTrusted: false,
    trustedUntil: null,
    lastLocation: null,
  },
];

export const mockPasswordChangedAt: Record<string, string | null> = {
  'd2c47314-4d08-4952-98b1-a1b8a6e22ef1': '2026-01-15T10:00:00Z',
  'user-002': '2025-11-20T14:30:00Z',
  'user-003': null,
  'user-004': null,
};
