// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/cms-seo.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const cmsSeoConstraints = {
  "SeoMetadataRequest": {
    "title": {
      "maxLength": 300
    },
    "titleTemplate": {
      "maxLength": 300
    },
    "description": {
      "maxLength": 2000
    },
    "keywords": {},
    "canonicalUrl": {
      "maxLength": 2048,
      "pattern": "^https://"
    },
    "robots": {},
    "openGraph": {},
    "twitterCard": {},
    "structuredDataExtras": {
      "maxLength": 32768
    },
    "disableAutoJsonLd": {},
    "alternateOverrides": {},
    "xDefaultCulture": {
      "maxLength": 20
    },
    "concurrencyStamp": {}
  },
  "SeoSuggestionApplyRequest": {
    "fields": {
      "required": true
    }
  },
  "SeoSuggestionRejectRequest": {
    "reason": {
      "maxLength": 1000
    }
  },
  "SeoSuggestRequest": {
    "siteId": {
      "required": true,
      "format": "uuid"
    },
    "contentType": {
      "required": true,
      "maxLength": 100
    },
    "contentId": {
      "required": true,
      "format": "uuid"
    },
    "contentTitle": {
      "required": true,
      "maxLength": 300
    },
    "scope": {
      "required": true
    },
    "culture": {
      "maxLength": 20
    },
    "contentBody": {
      "maxLength": 50000
    }
  },
  "SiteSeoDefaultsRequest": {
    "titleTemplate": {
      "maxLength": 300
    },
    "siteName": {
      "maxLength": 200
    },
    "defaultDescription": {
      "maxLength": 2000
    },
    "defaultRobots": {},
    "canonicalHost": {
      "maxLength": 2048,
      "pattern": "^https://"
    },
    "sitemapMaxUrlsPerFile": {
      "format": "int32",
      "minimum": 1,
      "maximum": 50000
    },
    "inheritFromParentPage": {},
    "defaultOpenGraph": {},
    "defaultTwitterCard": {},
    "defaultOgImage": {},
    "robotsTxtRules": {},
    "robotsTxtExtra": {
      "maxLength": 4096
    },
    "manifest": {},
    "enableAutomaticSeoGeneration": {},
    "concurrencyStamp": {}
  }
} satisfies Record<string, SchemaConstraints>;
