// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/ai-prompts.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const aiPromptsConstraints = {
  "CreatePromptRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "content": {
      "required": true,
      "maxLength": 20000
    },
    "shortDescription": {
      "maxLength": 500
    },
    "icon": {
      "maxLength": 100
    },
    "iconColor": {
      "granitValidator": "Validation:Format:ColorHex"
    },
    "categoryIds": {}
  },
  "UpdatePromptRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "content": {
      "required": true,
      "maxLength": 20000
    },
    "shortDescription": {
      "maxLength": 500
    },
    "icon": {
      "maxLength": 100
    },
    "iconColor": {
      "granitValidator": "Validation:Format:ColorHex"
    },
    "categoryIds": {}
  }
} satisfies Record<string, SchemaConstraints>;
