// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/webhooks.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const webhooksConstraints = {
  "WebhookSubscriptionCreateRequest": {
    "targetUrl": {
      "required": true,
      "maxLength": 2048,
      "granitValidator": "Validation:WebhookUrlBlockedTld"
    },
    "eventType": {
      "required": true,
      "maxLength": 200,
      "granitValidator": "Validation:UnknownWebhookEventType"
    }
  },
  "WebhookSubscriptionDeactivateRequest": {
    "reason": {
      "required": true,
      "maxLength": 1000
    }
  },
  "WebhookSubscriptionUpdateRequest": {
    "targetUrl": {
      "required": true,
      "maxLength": 2048,
      "granitValidator": "Validation:WebhookUrlBlockedTld"
    }
  }
} satisfies Record<string, SchemaConstraints>;
