// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/subscriptions.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const subscriptionsConstraints = {
  "BulkMigratePriceRequest": {
    "planId": {
      "required": true,
      "format": "uuid"
    },
    "newPlanPriceId": {
      "required": true,
      "format": "uuid"
    },
    "oldPlanPriceId": {
      "format": "uuid"
    }
  },
  "CreatePriceVersionRequest": {
    "amount": {
      "required": true,
      "pattern": "^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$",
      "format": "double",
      "minimum": 0
    },
    "currency": {
      "required": true,
      "maxLength": 3
    },
    "interval": {
      "required": true,
      "maxLength": 64
    },
    "productId": {
      "format": "uuid"
    }
  },
  "MigratePriceRequest": {
    "newPlanPriceId": {
      "required": true,
      "format": "uuid"
    }
  },
  "PlanCreateRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "pricingModel": {
      "required": true,
      "maxLength": 64
    },
    "defaultInterval": {
      "required": true,
      "maxLength": 64
    },
    "description": {
      "maxLength": 2000
    },
    "trialDays": {
      "format": "int32",
      "minimum": 0
    },
    "seatLimit": {
      "format": "int32",
      "exclusiveMinimum": 0
    }
  },
  "PlanUpdateRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "sortOrder": {
      "required": true,
      "format": "int32",
      "minimum": 0
    },
    "description": {
      "maxLength": 2000
    }
  },
  "SeatAssignRequest": {
    "userId": {
      "required": true,
      "format": "uuid"
    }
  },
  "SubscriptionCancelRequest": {
    "reason": {
      "maxLength": 500
    },
    "atPeriodEnd": {}
  },
  "SubscriptionChangePlanRequest": {
    "newPlanId": {
      "required": true,
      "format": "uuid"
    }
  },
  "SubscriptionCreateRequest": {
    "partyId": {
      "required": true,
      "format": "uuid"
    },
    "planId": {
      "required": true,
      "format": "uuid"
    },
    "currency": {
      "required": true,
      "maxLength": 3
    },
    "trialEndsAt": {
      "format": "date-time"
    }
  }
} satisfies Record<string, SchemaConstraints>;
