import { toEntityId, toISODateString } from '@granit/types';

import type {
  PlanPriceResponse,
  PlanResponse,
  SeatResponse,
  SubscriptionResponse,
} from '@granit/subscriptions';
import type { Mutable } from '@granit/testing';

export const mockPlans: Mutable<PlanResponse>[] = [
  {
    id: toEntityId<'Plan'>('plan-001'),
    name: 'Starter',
    description: 'Basic plan for small teams',
    pricingModel: 'Flat',
    defaultInterval: 'Monthly',
    trialDays: null,
    seatLimit: null,
    sortOrder: 0,
    lifecycleStatus: 'Draft',
    prices: [],
  },
  {
    id: toEntityId<'Plan'>('plan-002'),
    name: 'Professional',
    description: 'For growing businesses with advanced features',
    pricingModel: 'PerUnit',
    defaultInterval: 'Monthly',
    trialDays: 14,
    seatLimit: 50,
    sortOrder: 1,
    lifecycleStatus: 'Published',
    prices: [
      {
        id: toEntityId<'PlanPrice'>('price-002-1'),
        amount: 4900,
        currency: 'EUR',
        interval: 'Monthly',
        effectiveFrom: toISODateString('2025-11-15T00:00:00Z'),
        isCurrent: false,
        replacedByPriceId: toEntityId<'PlanPrice'>('price-002-2'),
        replacedAt: toISODateString('2026-01-01T00:00:00Z'),
      },
      {
        id: toEntityId<'PlanPrice'>('price-002-2'),
        amount: 5900,
        currency: 'EUR',
        interval: 'Monthly',
        effectiveFrom: toISODateString('2026-01-01T00:00:00Z'),
        isCurrent: false,
        replacedByPriceId: toEntityId<'PlanPrice'>('price-002-3'),
        replacedAt: toISODateString('2026-03-01T00:00:00Z'),
      },
      {
        id: toEntityId<'PlanPrice'>('price-002-3'),
        amount: 7900,
        currency: 'EUR',
        interval: 'Monthly',
        effectiveFrom: toISODateString('2026-03-01T00:00:00Z'),
        isCurrent: true,
        replacedByPriceId: null,
        replacedAt: null,
      },
    ],
  },
  {
    id: toEntityId<'Plan'>('plan-003'),
    name: 'Enterprise Legacy',
    description: 'Deprecated enterprise plan',
    pricingModel: 'Tiered',
    defaultInterval: 'Yearly',
    trialDays: null,
    seatLimit: null,
    sortOrder: 2,
    lifecycleStatus: 'Archived',
    prices: [
      {
        id: toEntityId<'PlanPrice'>('price-003-1'),
        amount: 99900,
        currency: 'EUR',
        interval: 'Yearly',
        effectiveFrom: toISODateString('2024-06-01T00:00:00Z'),
        isCurrent: false,
        replacedByPriceId: null,
        replacedAt: null,
      },
    ],
  },
];

export const mockPriceHistory: Record<string, Mutable<PlanPriceResponse>[]> = {
  'plan-002': [
    {
      id: toEntityId<'PlanPrice'>('price-002-1'),
      amount: 4900,
      currency: 'EUR',
      interval: 'Monthly',
      effectiveFrom: toISODateString('2025-11-15T00:00:00Z'),
      isCurrent: false,
      replacedByPriceId: toEntityId<'PlanPrice'>('price-002-2'),
      replacedAt: toISODateString('2026-01-01T00:00:00Z'),
    },
    {
      id: toEntityId<'PlanPrice'>('price-002-2'),
      amount: 5900,
      currency: 'EUR',
      interval: 'Monthly',
      effectiveFrom: toISODateString('2026-01-01T00:00:00Z'),
      isCurrent: false,
      replacedByPriceId: toEntityId<'PlanPrice'>('price-002-3'),
      replacedAt: toISODateString('2026-03-01T00:00:00Z'),
    },
    {
      id: toEntityId<'PlanPrice'>('price-002-3'),
      amount: 7900,
      currency: 'EUR',
      interval: 'Monthly',
      effectiveFrom: toISODateString('2026-03-01T00:00:00Z'),
      isCurrent: true,
      replacedByPriceId: null,
      replacedAt: null,
    },
  ],
  'plan-003': [
    {
      id: toEntityId<'PlanPrice'>('price-003-1'),
      amount: 99900,
      currency: 'EUR',
      interval: 'Yearly',
      effectiveFrom: toISODateString('2024-06-01T00:00:00Z'),
      isCurrent: false,
      replacedByPriceId: null,
      replacedAt: null,
    },
  ],
};

export const mockSubscriptions: Mutable<SubscriptionResponse>[] = [
  {
    id: toEntityId<'Subscription'>('sub-001'),
    partyId: toEntityId<'Party'>('party-001'),
    planId: toEntityId<'Plan'>('plan-002'),
    status: 'Active',
    currency: 'EUR',
    currentPeriodStart: toISODateString('2026-03-01T00:00:00Z'),
    currentPeriodEnd: toISODateString('2026-04-01T00:00:00Z'),
    trialEndsAt: null,
    cancelAtPeriodEnd: false,
    cancelledAt: null,
    cancellationReason: null,
    seatCount: 5,
    planPriceId: toEntityId<'PlanPrice'>('price-002-3'),
  },
  {
    id: toEntityId<'Subscription'>('sub-002'),
    partyId: toEntityId<'Party'>('party-002'),
    planId: toEntityId<'Plan'>('plan-002'),
    status: 'Trial',
    currency: 'EUR',
    currentPeriodStart: toISODateString('2026-03-15T00:00:00Z'),
    currentPeriodEnd: toISODateString('2026-04-14T00:00:00Z'),
    trialEndsAt: toISODateString('2026-04-14T00:00:00Z'),
    cancelAtPeriodEnd: false,
    cancelledAt: null,
    cancellationReason: null,
    seatCount: 2,
    planPriceId: toEntityId<'PlanPrice'>('price-002-3'),
  },
  {
    id: toEntityId<'Subscription'>('sub-003'),
    partyId: toEntityId<'Party'>('party-003'),
    planId: toEntityId<'Plan'>('plan-002'),
    status: 'PastDue',
    currency: 'EUR',
    currentPeriodStart: toISODateString('2026-02-01T00:00:00Z'),
    currentPeriodEnd: toISODateString('2026-03-01T00:00:00Z'),
    trialEndsAt: null,
    cancelAtPeriodEnd: false,
    cancelledAt: null,
    cancellationReason: null,
    seatCount: 3,
    planPriceId: toEntityId<'PlanPrice'>('price-002-3'),
  },
  {
    id: toEntityId<'Subscription'>('sub-004'),
    partyId: toEntityId<'Party'>('party-004'),
    planId: toEntityId<'Plan'>('plan-003'),
    status: 'Cancelled',
    currency: 'EUR',
    currentPeriodStart: toISODateString('2025-12-01T00:00:00Z'),
    currentPeriodEnd: toISODateString('2025-12-31T23:59:59Z'),
    trialEndsAt: null,
    cancelAtPeriodEnd: false,
    cancelledAt: toISODateString('2025-12-31T23:59:59Z'),
    cancellationReason: 'Migrating to new plan',
    seatCount: 10,
    planPriceId: toEntityId<'PlanPrice'>('price-003-1'),
  },
];

export const mockSeats: Record<string, Mutable<SeatResponse>[]> = {
  'sub-001': [
    {
      id: toEntityId<'Seat'>('seat-001'),
      userId: toEntityId<'User'>('user-002'),
      assignedAt: toISODateString('2025-12-01T10:30:00Z'),
    },
    {
      id: toEntityId<'Seat'>('seat-002'),
      userId: toEntityId<'User'>('user-004'),
      assignedAt: toISODateString('2025-12-05T14:00:00Z'),
    },
    {
      id: toEntityId<'Seat'>('seat-003'),
      userId: toEntityId<'User'>('user-009'),
      assignedAt: toISODateString('2026-01-10T09:15:00Z'),
    },
  ],
  'sub-002': [
    {
      id: toEntityId<'Seat'>('seat-004'),
      userId: toEntityId<'User'>('user-005'),
      assignedAt: toISODateString('2026-03-15T08:30:00Z'),
    },
  ],
};
