// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/metering.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const meteringConstraints = {
  "BackfillUsageRequest": {
    "events": {
      "required": true,
      "granitValidator": "Validation:Rule:MaxBatchSize"
    }
  },
  "DeprecateEventRequest": {
    "reason": {
      "required": true,
      "maxLength": 500
    }
  },
  "MeterDefinitionCreateRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "unit": {
      "required": true,
      "maxLength": 64
    },
    "aggregationType": {
      "required": true
    },
    "description": {
      "maxLength": 1024
    },
    "productId": {
      "format": "uuid"
    },
    "distinctProperty": {
      "maxLength": 200
    }
  },
  "MeterDefinitionUpdateRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "unit": {
      "required": true,
      "maxLength": 64
    },
    "description": {
      "maxLength": 1024
    }
  },
  "MeterEventRequest": {
    "meterDefinitionId": {
      "required": true,
      "format": "uuid"
    },
    "idempotencyKey": {
      "required": true
    },
    "quantity": {
      "required": true,
      "pattern": "^-?(?:0|[1-9]\\d*)(?:\\.\\d+)?$",
      "format": "double"
    },
    "timestamp": {
      "required": true,
      "format": "date-time"
    },
    "metadata": {}
  },
  "RecomputeUsageRequest": {
    "from": {
      "required": true,
      "format": "date-time"
    },
    "to": {
      "required": true,
      "format": "date-time"
    }
  },
  "RecordUsageRequest": {
    "events": {
      "required": true,
      "granitValidator": "Validation:Rule:MaxBatchSize"
    }
  }
} satisfies Record<string, SchemaConstraints>;
