import { toEntityId, toISODateString } from '@granit/types';

import type { ApiKeyResponse } from '@granit/authentication-api-keys';

export const mockApiKeys: ApiKeyResponse[] = [
  {
    id: toEntityId<'ApiKey'>('ak-1'),
    name: 'Patient Sync Service',
    type: 'Secret',
    environment: 'live',
    prefix: 'gk_live_sk_',
    lastFourChars: 'a1b2',
    permissions: ['read:patients', 'write:patients'],
    allowedCidrs: ['10.0.0.0/8'],
    expiresAt: null,
    lastUsedAt: toISODateString('2026-03-09T08:30:00Z'),
    revokedAt: null,
    cacheBehavior: 'Normal',
    createdAt: toISODateString('2025-11-15T10:00:00Z'),
  },
  {
    id: toEntityId<'ApiKey'>('ak-2'),
    name: 'Appointment Widget',
    type: 'Publishable',
    environment: 'live',
    prefix: 'gk_live_pk_',
    lastFourChars: 'c3d4',
    permissions: ['read:appointments'],
    allowedCidrs: [],
    expiresAt: toISODateString('2027-01-01T00:00:00Z'),
    lastUsedAt: toISODateString('2026-03-08T14:20:00Z'),
    revokedAt: null,
    cacheBehavior: 'Normal',
    createdAt: toISODateString('2025-12-01T09:00:00Z'),
  },
  {
    id: toEntityId<'ApiKey'>('ak-3'),
    name: 'Legacy Integration',
    type: 'Secret',
    environment: 'live',
    prefix: 'gk_live_sk_',
    lastFourChars: 'e5f6',
    permissions: ['read:patients'],
    allowedCidrs: ['192.168.1.0/24'],
    expiresAt: toISODateString('2026-01-01T00:00:00Z'),
    lastUsedAt: toISODateString('2025-12-28T16:00:00Z'),
    revokedAt: toISODateString('2026-01-15T09:00:00Z'),
    cacheBehavior: 'Normal',
    createdAt: toISODateString('2025-06-01T08:00:00Z'),
  },
  {
    id: toEntityId<'ApiKey'>('ak-4'),
    name: 'Webhook Delivery Service',
    type: 'Webhook',
    environment: 'test',
    prefix: 'gk_test_wh_',
    lastFourChars: 'g7h8',
    permissions: ['webhook:deliver'],
    allowedCidrs: [],
    expiresAt: null,
    lastUsedAt: toISODateString('2026-03-09T10:00:00Z'),
    revokedAt: null,
    cacheBehavior: 'NoCache',
    createdAt: toISODateString('2026-01-10T11:00:00Z'),
  },
  {
    id: toEntityId<'ApiKey'>('ak-5'),
    name: 'CI/CD Pipeline Token',
    type: 'Ephemeral',
    environment: 'dev',
    prefix: 'gk_dev_eph_',
    lastFourChars: 'i9j0',
    permissions: ['read:config'],
    allowedCidrs: ['172.16.0.0/12'],
    expiresAt: toISODateString('2026-03-10T00:00:00Z'),
    lastUsedAt: null,
    revokedAt: null,
    cacheBehavior: 'NoCache',
    createdAt: toISODateString('2026-03-09T08:00:00Z'),
  },
];
