// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/cms-hostnames.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const cmsHostnamesConstraints = {
  "SiteHostnameCreateRequest": {
    "host": {
      "required": true,
      "maxLength": 253
    },
    "isPrimary": {}
  }
} satisfies Record<string, SchemaConstraints>;
