// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/catalog.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const catalogConstraints = {
  "AddProductExternalMappingRequest": {
    "providerName": {
      "required": true,
      "maxLength": 64
    },
    "externalId": {
      "required": true,
      "maxLength": 256
    }
  },
  "ProductCreateRequest": {
    "sku": {
      "required": true,
      "maxLength": 64
    },
    "name": {
      "required": true,
      "maxLength": 200
    },
    "type": {
      "required": true,
      "maxLength": 64
    },
    "unit": {
      "required": true,
      "maxLength": 64
    },
    "description": {
      "maxLength": 2000
    }
  },
  "ProductUpdateRequest": {
    "name": {
      "required": true,
      "maxLength": 200
    },
    "unit": {
      "required": true,
      "maxLength": 64
    },
    "description": {
      "maxLength": 2000
    }
  },
  "UpdateProductMetadataRequest": {
    "metadata": {
      "required": true
    }
  }
} satisfies Record<string, SchemaConstraints>;
