// GENERATED by scripts/generate-front-constraints.mjs — DO NOT EDIT.
// Source: contracts/openapi/privacy.json
// Validation constraints derived from the OpenAPI contract (the single source of
// truth). Consumed via createConstraintsResolver from @granit/react-validation.
// Regenerated on pre-commit when the spec or the generator changes.

import type { SchemaConstraints } from '@granit/validation';

export const privacyConstraints = {
  "LegalDocumentCreateRequest": {
    "documentId": {
      "required": true,
      "maxLength": 200
    },
    "displayName": {
      "required": true,
      "maxLength": 500
    },
    "description": {
      "maxLength": 2000
    },
    "templateName": {
      "maxLength": 500
    }
  },
  "LegalDocumentUpdateRequest": {
    "displayName": {
      "required": true,
      "maxLength": 500
    },
    "concurrencyStamp": {
      "required": true
    },
    "description": {
      "maxLength": 2000
    },
    "templateName": {
      "maxLength": 500
    },
    "documentBlobId": {
      "format": "uuid"
    }
  },
  "PrivacyAcceptAgreementRequest": {
    "documentId": {
      "required": true,
      "maxLength": 200
    },
    "version": {
      "required": true,
      "maxLength": 50
    }
  },
  "PrivacyDeletionRequest": {
    "reason": {
      "required": true,
      "maxLength": 2000
    },
    "defer": {}
  },
  "PrivacyExportOnBehalfOfRequest": {
    "subjectUserId": {
      "required": true,
      "format": "uuid"
    },
    "scopes": {
      "maxLength": 200
    }
  },
  "PrivacyExportRequest": {
    "scopes": {
      "maxLength": 200
    }
  }
} satisfies Record<string, SchemaConstraints>;
